package src

trait Angle_value_table {
  val colors_map_a: Map[String, Map[String, Array[Char]]] =
    Map[String, Map[String, Array[Char]]](
    "a__0" -> Map[String, Array[Char]](
      "ful1" -> Array('w', 'b', 'o'),
      "ful2" -> Array('o', 'w', 'b'),
      "ful3" -> Array('b', 'o', 'w'),
      "fur1" -> Array('w', 'b', 'o'),
      "fur2" -> Array('o', 'w', 'b'),
      "fur3" -> Array('b', 'o', 'w'),
      "fdl1" -> Array('w', 'o', 'b'),
      "fdl2" -> Array('b', 'w', 'o'),
      "fdl3" -> Array('o', 'b', 'w'),
      "fdr1" -> Array('w', 'o', 'b'),
      "fdr2" -> Array('b', 'w', 'o'),
      "fdr3" -> Array('o', 'b', 'w'),
      "bul1" -> Array('w', 'b', 'o'),
      "bul2" -> Array('o', 'w', 'b'),
      "bul3" -> Array('b', 'o', 'w'),
      "bur1" -> Array('w', 'o', 'b'),
      "bur2" -> Array('b', 'w', 'o'),
      "bur3" -> Array('o', 'b', 'w'),
      "bdl1" -> Array('w', 'o', 'b'),
      "bdl2" -> Array('b', 'w', 'o'),
      "bdl3" -> Array('o', 'b', 'w'),
      "bdr1" -> Array('w', 'b', 'o'),
      "bdr2" -> Array('o', 'w', 'b'),
      "bdr3" -> Array('b', 'o', 'w')
    ),
      "a__1" -> Map[String, Array[Char]](
        "ful1" -> Array('w', 'r', 'b'),
        "ful2" -> Array('b', 'w', 'r'),
        "ful3" -> Array('r', 'b', 'w'),
        "fur1" -> Array('w', 'r', 'b'),
        "fur2" -> Array('b', 'w', 'r'),
        "fur3" -> Array('r', 'b', 'w'),
        "fdl1" -> Array('w', 'b', 'r'),
        "fdl2" -> Array('r', 'w', 'b'),
        "fdl3" -> Array('b', 'r', 'w'),
        "fdr1" -> Array('w', 'b', 'r'),
        "fdr2" -> Array('r', 'w', 'b'),
        "fdr3" -> Array('b', 'r', 'w'),
        "bul1" -> Array('w', 'r', 'b'),
        "bul2" -> Array('b', 'w', 'r'),
        "bul3" -> Array('r', 'b', 'w'),
        "bur1" -> Array('w', 'b', 'r'),
        "bur2" -> Array('r', 'w', 'b'),
        "bur3" -> Array('b', 'r', 'w'),
        "bdl1" -> Array('w', 'b', 'r'),
        "bdl2" -> Array('r', 'w', 'b'),
        "bdl3" -> Array('b', 'r', 'w'),
        "bdr1" -> Array('w', 'r', 'b'),
        "bdr2" -> Array('b', 'w', 'r'),
        "bdr3" -> Array('r', 'b', 'w')
    ),
      "a__2" -> Map[String, Array[Char]](
        "ful1" -> Array('w', 'o', 'g'),
        "ful2" -> Array('g', 'w', 'o'),
        "ful3" -> Array('o', 'g', 'w'),
        "fur1" -> Array('w', 'o', 'g'),
        "fur2" -> Array('g', 'w', 'o'),
        "fur3" -> Array('o', 'g', 'w'),
        "fdl1" -> Array('w', 'g', 'o'),
        "fdl2" -> Array('o', 'w', 'g'),
        "fdl3" -> Array('g', 'o', 'w'),
        "fdr1" -> Array('w', 'g', 'o'),
        "fdr2" -> Array('o', 'w', 'g'),
        "fdr3" -> Array('g', 'o', 'w'),
        "bul1" -> Array('w', 'o', 'g'),
        "bul2" -> Array('g', 'w', 'o'),
        "bul3" -> Array('o', 'g', 'w'),
        "bur1" -> Array('w', 'g', 'o'),
        "bur2" -> Array('o', 'w', 'g'),
        "bur3" -> Array('g', 'o', 'w'),
        "bdl1" -> Array('w', 'g', 'o'),
        "bdl2" -> Array('o', 'w', 'g'),
        "bdl3" -> Array('g', 'o', 'w'),
        "bdr1" -> Array('w', 'o', 'g'),
        "bdr2" -> Array('g', 'w', 'o'),
        "bdr3" -> Array('o', 'g', 'w')
    ),
      "a__3" -> Map[String, Array[Char]](
        "ful1" -> Array('w', 'g', 'r'),
        "ful2" -> Array('r', 'w', 'g'),
        "ful3" -> Array('g', 'r', 'w'),
        "fur1" -> Array('w', 'g', 'r'),
        "fur2" -> Array('r', 'w', 'g'),
        "fur3" -> Array('g', 'r', 'w'),
        "fdl1" -> Array('w', 'r', 'g'),
        "fdl2" -> Array('g', 'w', 'r'),
        "fdl3" -> Array('r', 'g', 'w'),
        "fdr1" -> Array('w', 'r', 'g'),
        "fdr2" -> Array('g', 'w', 'r'),
        "fdr3" -> Array('r', 'g', 'w'),
        "bul1" -> Array('w', 'g', 'r'),
        "bul2" -> Array('r', 'w', 'g'),
        "bul3" -> Array('g', 'r', 'w'),
        "bur1" -> Array('w', 'r', 'g'),
        "bur2" -> Array('g', 'w', 'r'),
        "bur3" -> Array('r', 'g', 'w'),
        "bdl1" -> Array('w', 'r', 'g'),
        "bdl2" -> Array('g', 'w', 'r'),
        "bdl3" -> Array('r', 'g', 'w'),
        "bdr1" -> Array('w', 'g', 'r'),
        "bdr2" -> Array('r', 'w', 'g'),
        "bdr3" -> Array('g', 'r', 'w')
    ),
      "a__4" -> Map[String, Array[Char]](
        "ful1" -> Array('o', 'y', 'g'),
        "ful2" -> Array('g', 'o', 'y'),
        "ful3" -> Array('y', 'g', 'o'),
        "fur1" -> Array('o', 'y', 'g'),
        "fur2" -> Array('g', 'o', 'y'),
        "fur3" -> Array('y', 'g', 'o'),
        "fdl1" -> Array('o', 'g', 'y'),
        "fdl2" -> Array('y', 'o', 'g'),
        "fdl3" -> Array('g', 'y', 'o'),
        "fdr1" -> Array('o', 'g', 'y'),
        "fdr2" -> Array('y', 'o', 'g'),
        "fdr3" -> Array('g', 'y', 'o'),
        "bul1" -> Array('o', 'y', 'g'),
        "bul2" -> Array('g', 'o', 'y'),
        "bul3" -> Array('y', 'g', 'o'),
        "bur1" -> Array('o', 'g', 'y'),
        "bur2" -> Array('y', 'o', 'g'),
        "bur3" -> Array('g', 'y', 'o'),
        "bdl1" -> Array('o', 'g', 'y'),
        "bdl2" -> Array('y', 'o', 'g'),
        "bdl3" -> Array('g', 'y', 'o'),
        "bdr1" -> Array('o', 'y', 'g'),
        "bdr2" -> Array('g', 'o', 'y'),
        "bdr3" -> Array('y', 'g', 'o')
    ),
      "a__5" -> Map[String, Array[Char]](
        "ful1" -> Array('g', 'y', 'r'),
        "ful2" -> Array('r', 'g', 'y'),
        "ful3" -> Array('y', 'r', 'g'),
        "fur1" -> Array('g', 'y', 'r'),
        "fur2" -> Array('r', 'g', 'y'),
        "fur3" -> Array('y', 'r', 'g'),
        "fdl1" -> Array('g', 'r', 'y'),
        "fdl2" -> Array('y', 'g', 'r'),
        "fdl3" -> Array('r', 'y', 'g'),
        "fdr1" -> Array('g', 'r', 'y'),
        "fdr2" -> Array('y', 'g', 'r'),
        "fdr3" -> Array('r', 'y', 'g'),
        "bul1" -> Array('g', 'y', 'r'),
        "bul2" -> Array('r', 'g', 'y'),
        "bul3" -> Array('y', 'r', 'g'),
        "bur1" -> Array('g', 'r', 'y'),
        "bur2" -> Array('y', 'g', 'r'),
        "bur3" -> Array('r', 'y', 'g'),
        "bdl1" -> Array('g', 'r', 'y'),
        "bdl2" -> Array('y', 'g', 'r'),
        "bdl3" -> Array('r', 'y', 'g'),
        "bdr1" -> Array('g', 'y', 'r'),
        "bdr2" -> Array('r', 'g', 'y'),
        "bdr3" -> Array('y', 'r', 'g')
    ),
      "a__6" -> Map[String, Array[Char]](
        "ful1" -> Array('o', 'b', 'y'),
        "ful2" -> Array('y', 'o', 'b'),
        "ful3" -> Array('b', 'y', 'o'),
        "fur1" -> Array('o', 'b', 'y'),
        "fur2" -> Array('y', 'o', 'b'),
        "fur3" -> Array('b', 'y', 'o'),
        "fdl1" -> Array('o', 'y', 'b'),
        "fdl2" -> Array('b', 'o', 'y'),
        "fdl3" -> Array('y', 'b', 'o'),
        "fdr1" -> Array('o', 'y', 'b'),
        "fdr2" -> Array('b', 'o', 'y'),
        "fdr3" -> Array('y', 'b', 'o'),
        "bul1" -> Array('o', 'b', 'y'),
        "bul2" -> Array('y', 'o', 'b'),
        "bul3" -> Array('b', 'y', 'o'),
        "bur1" -> Array('o', 'y', 'b'),
        "bur2" -> Array('b', 'o', 'y'),
        "bur3" -> Array('y', 'b', 'o'),
        "bdl1" -> Array('o', 'y', 'b'),
        "bdl2" -> Array('b', 'o', 'y'),
        "bdl3" -> Array('y', 'b', 'o'),
        "bdr1" -> Array('o', 'b', 'y'),
        "bdr2" -> Array('y', 'o', 'b'),
        "bdr3" -> Array('b', 'y', 'o')
    ),
      "a__7" -> Map[String, Array[Char]](
        "ful1" -> Array('r', 'y', 'b'),
        "ful2" -> Array('b', 'r', 'y'),
        "ful3" -> Array('y', 'b', 'r'),
        "fur1" -> Array('r', 'y', 'b'),
        "fur2" -> Array('b', 'r', 'y'),
        "fur3" -> Array('y', 'b', 'r'),
        "fdl1" -> Array('r', 'b', 'y'),
        "fdl2" -> Array('y', 'r', 'b'),
        "fdl3" -> Array('b', 'y', 'r'),
        "fdr1" -> Array('r', 'b', 'y'),
        "fdr2" -> Array('y', 'r', 'b'),
        "fdr3" -> Array('b', 'y', 'r'),
        "bul1" -> Array('r', 'y', 'b'),
        "bul2" -> Array('b', 'r', 'y'),
        "bul3" -> Array('y', 'b', 'r'),
        "bur1" -> Array('r', 'b', 'y'),
        "bur2" -> Array('y', 'r', 'b'),
        "bur3" -> Array('b', 'y', 'r'),
        "bdl1" -> Array('r', 'b', 'y'),
        "bdl2" -> Array('y', 'r', 'b'),
        "bdl3" -> Array('b', 'y', 'r'),
        "bdr1" -> Array('r', 'y', 'b'),
        "bdr2" -> Array('b', 'r', 'y'),
        "bdr3" -> Array('y', 'b', 'r')
    )
  )
}
