/*
    Collection for get steps for movie side elem for second layer solve

    (<current_position>, <target_position>, <start_side>) -> <needed_movies>
 */

package src

trait Collection_side_movies_second_layer {
  val collectionSideMoviesSecondLayer = Map(
    // start side: up
    (Side_elem_position.fl1, Side_elem_position.fl1, Side_position.up) -> Array(""),
    (Side_elem_position.fl2, Side_elem_position.fl1, Side_position.up) -> Array("L", "D2", "L'", "D", "L", "D2", "L'", "D", "F'", "D'", "F"),
    (Side_elem_position.fr1, Side_elem_position.fl1, Side_position.up) -> Array("R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.fr2, Side_elem_position.fl1, Side_position.up) -> Array("R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.bl1, Side_elem_position.fl1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.bl2, Side_elem_position.fl1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.br1, Side_elem_position.fl1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.br2, Side_elem_position.fl1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.fd1, Side_elem_position.fl1, Side_position.up) -> Array("R2", "F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fd2, Side_elem_position.fl1, Side_position.up) -> Array("D", "L", "D'", "L'", "D'", "F'", "D", "F"),
    (Side_elem_position.rd1, Side_elem_position.fl1, Side_position.up) -> Array("R", "F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.rd2, Side_elem_position.fl1, Side_position.up) -> Array("L", "D'", "L'", "D'", "F'", "D", "F"),
    (Side_elem_position.bd1, Side_elem_position.fl1, Side_position.up) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.bd2, Side_elem_position.fl1, Side_position.up) -> Array("D'", "L", "D'", "L'", "D'", "F'", "D", "F"),
    (Side_elem_position.ld1, Side_elem_position.fl1, Side_position.up) -> Array("R'", "F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.ld2, Side_elem_position.fl1, Side_position.up) -> Array("D2", "L", "D'", "L'", "D'", "F'", "D", "F"),

    (Side_elem_position.fl1, Side_elem_position.fr1, Side_position.up) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fl2, Side_elem_position.fr1, Side_position.up) -> Array("F'", "R", "F", "R D", "R'", "D'"),
    (Side_elem_position.fr1, Side_elem_position.fr1, Side_position.up) -> Array(""),
    (Side_elem_position.fr2, Side_elem_position.fr1, Side_position.up) -> Array("F", "D2", "F'", "D", "F", "D2", "F'", "D", "R'", "D'", "R"),
    (Side_elem_position.bl1, Side_elem_position.fr1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.bl2, Side_elem_position.fr1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.br1, Side_elem_position.fr1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.br2, Side_elem_position.fr1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.fd1, Side_elem_position.fr1, Side_position.up) -> Array("D'", "R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.fd2, Side_elem_position.fr1, Side_position.up) -> Array("D2", "F", "D'", "F'", "D'", "R'", "D", "R"),
    (Side_elem_position.rd1, Side_elem_position.fr1, Side_position.up) -> Array("D2", "R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.rd2, Side_elem_position.fr1, Side_position.up) -> Array("D", "F", "D'", "F'", "D'", "R'", "D", "R"),
    (Side_elem_position.bd1, Side_elem_position.fr1, Side_position.up) -> Array("D", "R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.bd2, Side_elem_position.fr1, Side_position.up) -> Array("F", "D'", "F'", "D'", "R'", "D", "R"),
    (Side_elem_position.ld1, Side_elem_position.fr1, Side_position.up) -> Array("R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.ld2, Side_elem_position.fr1, Side_position.up) -> Array("D'", "F", "D'", "F'", "D'", "R'", "D", "R"),

    (Side_elem_position.fl1, Side_elem_position.bl1, Side_position.up) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fl2, Side_elem_position.bl1, Side_position.up) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fr1, Side_elem_position.bl1, Side_position.up) -> Array("R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.fr2, Side_elem_position.bl1, Side_position.up) -> Array("R' ", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.bl1, Side_elem_position.bl1, Side_position.up) -> Array(""),
    (Side_elem_position.bl2, Side_elem_position.bl1, Side_position.up) -> Array("R", "D2", "R'", "D", "R", "D2", "R'", "D", "B'", "D'", "B"),
    (Side_elem_position.br1, Side_elem_position.bl1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "U'", "B'"),
    (Side_elem_position.br2, Side_elem_position.bl1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.fd1, Side_elem_position.bl1, Side_position.up) -> Array("B'", "D", "B", "D", "R", "D'", "R'"),
    (Side_elem_position.fd2, Side_elem_position.bl1, Side_position.up) -> Array("D'", "R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.rd1, Side_elem_position.bl1, Side_position.up) -> Array("D'", "B'", "D", "B", "D", "R", "D'", "R'"),
    (Side_elem_position.rd2, Side_elem_position.bl1, Side_position.up) -> Array("D2", "R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.bd1, Side_elem_position.bl1, Side_position.up) -> Array("D2", "B'", "D", "B", "D", "R", "D'", "R'"),
    (Side_elem_position.bd2, Side_elem_position.bl1, Side_position.up) -> Array("D", "R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.ld1, Side_elem_position.bl1, Side_position.up) -> Array("D", "B'", "D", "B", "D", "R", "D'", "R'"),
    (Side_elem_position.ld2, Side_elem_position.bl1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),

    (Side_elem_position.fl1, Side_elem_position.br1, Side_position.up) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fl2, Side_elem_position.br1, Side_position.up) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fr1, Side_elem_position.br1, Side_position.up) -> Array("R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.fr2, Side_elem_position.br1, Side_position.up) -> Array("R'", "D", "R", "D", "F", "D'", "F'"),
    (Side_elem_position.bl1, Side_elem_position.br1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.bl2, Side_elem_position.br1, Side_position.up) -> Array("R", "D'", "R'", "D'", "B'", "D", "B"),
    (Side_elem_position.br1, Side_elem_position.br1, Side_position.up) -> Array(""),
    (Side_elem_position.br2, Side_elem_position.br1, Side_position.up) -> Array("B", "D2", "B'", "D", "B", "D2", "B'", "D", "L'", "D'", "L"),
    (Side_elem_position.fd1, Side_elem_position.br1, Side_position.up) -> Array("B", "D'", "B'", "D'", "L'", "D", "L"),
    (Side_elem_position.fd2, Side_elem_position.br1, Side_position.up) -> Array("D", "L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.rd1, Side_elem_position.br1, Side_position.up) -> Array("D'", "B", "D'", "B'", "D'", "L'", "D", "L"),
    (Side_elem_position.rd2, Side_elem_position.br1, Side_position.up) -> Array("L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.bd1, Side_elem_position.br1, Side_position.up) -> Array("D2", "B", "D'", "B'", "D'", "L'", "D", "L"),
    (Side_elem_position.bd2, Side_elem_position.br1, Side_position.up) -> Array("D'", "L'", "D", "L", "D", "B", "D'", "B'"),
    (Side_elem_position.ld1, Side_elem_position.br1, Side_position.up) -> Array("D", "B", "D'", "B'", "D'", "L'", "D", "L"),
    (Side_elem_position.ld2, Side_elem_position.br1, Side_position.up) -> Array("D2", "L'", "D", "L", "B", "D'", "B'"),

    // start side: left
    (Side_elem_position.fu1, Side_elem_position.fu1, Side_position.left) -> Array(""),
    (Side_elem_position.fu2, Side_elem_position.fu1, Side_position.left) -> Array("F", "R2", "F'", "R", "F", "R2", "F'", "R", "U'", "R'", "U"),
    (Side_elem_position.fd1, Side_elem_position.fu1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fd2, Side_elem_position.fu1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.bu1, Side_elem_position.fu1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bu2, Side_elem_position.fu1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bd1, Side_elem_position.fu1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.bd2, Side_elem_position.fu1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.fr1, Side_elem_position.fu1, Side_position.left) -> Array("R2", "F", "R'", "F'", "R'", "U'", "R", "U"),
    (Side_elem_position.fr2, Side_elem_position.fu1, Side_position.left) -> Array("R'", "U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.ru1, Side_elem_position.fu1, Side_position.left) -> Array("R", "F", "R'", "F'", "R'", "U'", "R", "U"),
    (Side_elem_position.ru2, Side_elem_position.fu1, Side_position.left) -> Array("R2", "U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.bl1, Side_elem_position.fu1, Side_position.left) -> Array("R", "U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.bl2, Side_elem_position.fu1, Side_position.left) -> Array("F", "R'", "F'", "R'", "U'", "R", "U"),
    (Side_elem_position.rd1, Side_elem_position.fu1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.rd2, Side_elem_position.fu1, Side_position.left) -> Array("R'", "F", "R'", "F'", "R'", "U'", "R", "U"),

    (Side_elem_position.fu1, Side_elem_position.fd1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.fu2, Side_elem_position.fd1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.fd1, Side_elem_position.fd1, Side_position.left) -> Array(""),
    (Side_elem_position.fd2, Side_elem_position.fd1, Side_position.left) -> Array("D", "R2", "D'", "R", "D", "R2", "D'", "R", "F'", "R'", "F"),
    (Side_elem_position.bu1, Side_elem_position.fd1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bu2, Side_elem_position.fd1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bd1, Side_elem_position.fd1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.bd2, Side_elem_position.fd1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.fr1, Side_elem_position.fd1, Side_position.left) -> Array("R", "D", "R'", "D'", "R'", "F'", "R", "F"),
    (Side_elem_position.fr2, Side_elem_position.fd1, Side_position.left) -> Array("R2", "F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.ru1, Side_elem_position.fd1, Side_position.left) -> Array("D", "R'", "D'", "R'", "F'", "R", "F"),
    (Side_elem_position.ru2, Side_elem_position.fd1, Side_position.left) -> Array("R", "F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.bl1, Side_elem_position.fd1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.bl2, Side_elem_position.fd1, Side_position.left) -> Array("R'", "D", "R'", "D'", "R'", "F'", "R", "F"),
    (Side_elem_position.rd1, Side_elem_position.fd1, Side_position.left) -> Array("R'", "F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.rd2, Side_elem_position.fd1, Side_position.left) -> Array("R2", "D", "R'", "D'", "R'", "F'", "R", "F"),

    (Side_elem_position.fu1, Side_elem_position.bu1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.fu2, Side_elem_position.bu1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.fd1, Side_elem_position.bu1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fd2, Side_elem_position.bu1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.bu1, Side_elem_position.bu1, Side_position.left) -> Array(""),
    (Side_elem_position.bu2, Side_elem_position.bu1, Side_position.left) -> Array("U", "R2", "U'", "R", "U", "R2", "U'", "R", "B'", "R'", "B"),
    (Side_elem_position.bd1, Side_elem_position.bu1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.bd2, Side_elem_position.bu1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.fr1, Side_elem_position.bu1, Side_position.left) -> Array("B'", "R", "B", "R", "U", "R'", "U'"),
    (Side_elem_position.fr2, Side_elem_position.bu1, Side_position.left) -> Array("R'", "U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.ru1, Side_elem_position.bu1, Side_position.left) -> Array("R'", "B'", "R", "B", "R", "U", "R'", "U'"),
    (Side_elem_position.ru2, Side_elem_position.bu1, Side_position.left) -> Array("R2", "U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bl1, Side_elem_position.bu1, Side_position.left) -> Array("R", "U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bl2, Side_elem_position.bu1, Side_position.left) -> Array("R2", "B'", "R", "B", "R", "U", "R'", "U'"),
    (Side_elem_position.rd1, Side_elem_position.bu1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.rd2, Side_elem_position.bu1, Side_position.left) -> Array("R", "B'", "R", "B", "R", "U", "R'", "U'"),

    (Side_elem_position.fu1, Side_elem_position.bd1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.fu2, Side_elem_position.bd1, Side_position.left) -> Array("U'", "R", "U", "R", "F", "R'", "F'"),
    (Side_elem_position.fd1, Side_elem_position.bd1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.fd2, Side_elem_position.bd1, Side_position.left) -> Array("F'", "R", "F", "R", "D", "R'", "D'"),
    (Side_elem_position.bu1, Side_elem_position.bd1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bu2, Side_elem_position.bd1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B'", "R", "B"),
    (Side_elem_position.bd1, Side_elem_position.bd1, Side_position.left) -> Array(""),
    (Side_elem_position.bd2, Side_elem_position.bd1, Side_position.left) -> Array("B", "R2", "B'", "R", "B", "R2", "B'", "R", "D'", "R'", "D"),
    (Side_elem_position.fr1, Side_elem_position.bd1, Side_position.left) -> Array("R", "D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.fr2, Side_elem_position.bd1, Side_position.left) -> Array("B", "R'", "B'", "R'", "D'", "R", "D"),
    (Side_elem_position.ru1, Side_elem_position.bd1, Side_position.left) -> Array("D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.ru2, Side_elem_position.bd1, Side_position.left) -> Array("R'", "B", "R'", "B'", "R'", "D'", "R", "D"),
    (Side_elem_position.bl1, Side_elem_position.bd1, Side_position.left) -> Array("R2", "B", "R'", "B'", "R'", "D'", "R", "D"),
    (Side_elem_position.bl2, Side_elem_position.bd1, Side_position.left) -> Array("R'", "D'", "R", "D", "R", "B", "R'", "B'"),
    (Side_elem_position.rd1, Side_elem_position.bd1, Side_position.left) -> Array("R", "B", "R'", "B'", "R'", "D'", "R", "D"),
    (Side_elem_position.rd2, Side_elem_position.bd1, Side_position.left) -> Array("R2", "D'", "R", "D", "R", "B", "R'", "B'"),

    // start side: front
    (Side_elem_position.lu1, Side_elem_position.lu1, Side_position.front) -> Array(""),
    (Side_elem_position.lu2, Side_elem_position.lu1, Side_position.front) -> Array("U", "B2", "U'", "B", "U", "B2", "U'", "B", "L'", "B'", "L"),
    (Side_elem_position.ld1, Side_elem_position.lu1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.ld2, Side_elem_position.lu1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.ru1, Side_elem_position.lu1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.ru2, Side_elem_position.lu1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.rd1, Side_elem_position.lu1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.rd2, Side_elem_position.lu1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.bu1, Side_elem_position.lu1, Side_position.front) -> Array("B'", "L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.bu2, Side_elem_position.lu1, Side_position.front) -> Array("B2", "U", "B'", "U'", "B'", "L'", "B", "L"),
    (Side_elem_position.bl1, Side_elem_position.lu1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.bl2, Side_elem_position.lu1, Side_position.front) -> Array("B'", "U", "B'", "U'", "B'", "L'", "B", "L"),
    (Side_elem_position.br1, Side_elem_position.lu1, Side_position.front) -> Array("B", "U", "B'", "U'", "B'", "L'", "B", "L"),
    (Side_elem_position.br2, Side_elem_position.lu1, Side_position.front) -> Array("B2", "L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.bd1, Side_elem_position.lu1, Side_position.front) -> Array("U ", "B'", "U'", "B'", "L'", "B", "L"),
    (Side_elem_position.bd2, Side_elem_position.lu1, Side_position.front) -> Array("B", "L'", "B", "L", "B", "U", "B'", "U'"),

    (Side_elem_position.lu1, Side_elem_position.ld1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.lu2, Side_elem_position.ld1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.ld1, Side_elem_position.ld1, Side_position.front) -> Array(""),
    (Side_elem_position.ld2, Side_elem_position.ld1, Side_position.front) -> Array("L", "B2", "L'", "B", "L", "B2", "L'", "B", "D'", "B'", "D"),
    (Side_elem_position.ru1, Side_elem_position.ld1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.ru2, Side_elem_position.ld1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.rd1, Side_elem_position.ld1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.rd2, Side_elem_position.ld1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.bu1, Side_elem_position.ld1, Side_position.front) -> Array("D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.bu2, Side_elem_position.ld1, Side_position.front) -> Array("B'", "L", "B'", "L'", "B'", "D'", "B", "D"),
    (Side_elem_position.bl1, Side_elem_position.ld1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.bl2, Side_elem_position.ld1, Side_position.front) -> Array("L", "B'", "L'", "B'", "D'", "B", "D"),
    (Side_elem_position.br1, Side_elem_position.ld1, Side_position.front) -> Array("B'", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.br2, Side_elem_position.ld1, Side_position.front) -> Array("B2", "L", "B'", "L'", "B'", "D'", "B", "D"),
    (Side_elem_position.bd1, Side_elem_position.ld1, Side_position.front) -> Array("B", "L", "B'", "L'", "B'", "D'", "B", "D"),
    (Side_elem_position.bd2, Side_elem_position.ld1, Side_position.front) -> Array("B2", "D'", "B", "D", "B", "L", "B'", "L'"),

    (Side_elem_position.lu1, Side_elem_position.ru1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.lu2, Side_elem_position.ru1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.ld1, Side_elem_position.ru1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.ld2, Side_elem_position.ru1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.ru1, Side_elem_position.ru1, Side_position.front) -> Array(""),
    (Side_elem_position.ru2, Side_elem_position.ru1, Side_position.front) -> Array("R", "B2", "R'", "B", "R", "B2", "R'", "B", "U'", "B'", "U"),
    (Side_elem_position.rd1, Side_elem_position.ru1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.rd2, Side_elem_position.ru1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.bu1, Side_elem_position.ru1, Side_position.front) -> Array("B", "R", "B'", "R'", "B'", "U'", "B", "U"),
    (Side_elem_position.bu2, Side_elem_position.ru1, Side_position.front) -> Array("B2", "U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.bl1, Side_elem_position.ru1, Side_position.front) -> Array("B2", "R", "B'", "R'", "B'", "U'", "B", "U"),
    (Side_elem_position.bl2, Side_elem_position.ru1, Side_position.front) -> Array("B'", "U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.br1, Side_elem_position.ru1, Side_position.front) -> Array("R", "B'", "R'", "B'", "U'", "B", "U"),
    (Side_elem_position.br2, Side_elem_position.ru1, Side_position.front) -> Array("B", "U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.bd1, Side_elem_position.ru1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.bd2, Side_elem_position.ru1, Side_position.front) -> Array("B'", "R", "B'", "R'", "B'", "U'", "B", "U"),

    (Side_elem_position.lu1, Side_elem_position.rd1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.lu2, Side_elem_position.rd1, Side_position.front) -> Array("L'", "B", "L", "B", "U", "B'", "U'"),
    (Side_elem_position.ld1, Side_elem_position.rd1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.ld2, Side_elem_position.rd1, Side_position.front) -> Array("B", "D'", "B", "D", "B", "L", "B'", "L'"),
    (Side_elem_position.ru1, Side_elem_position.rd1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.ru2, Side_elem_position.rd1, Side_position.front) -> Array("U'", "B", "U", "B", "R", "B'", "R'"),
    (Side_elem_position.rd1, Side_elem_position.rd1, Side_position.front) -> Array(""),
    (Side_elem_position.rd2, Side_elem_position.rd1, Side_position.front) -> Array("D", "B2", "D'", "B", "D", "B2", "D'", "B", "R'", "B'", "R"),
    (Side_elem_position.bu1, Side_elem_position.rd1, Side_position.front) -> Array("D", "B'", "D'", "B'", "R'", "B", "R"),
    (Side_elem_position.bu2, Side_elem_position.rd1, Side_position.front) -> Array("B", "R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.bl1, Side_elem_position.rd1, Side_position.front) -> Array("B", "D", "B'", "D'", "B'", "R'", "B", "R"),
    (Side_elem_position.bl2, Side_elem_position.rd1, Side_position.front) -> Array("B2", "R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.br1, Side_elem_position.rd1, Side_position.front) -> Array("B'", "D", "B'", "D'", "B'", "R'", "B", "R"),
    (Side_elem_position.br2, Side_elem_position.rd1, Side_position.front) -> Array("R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.bd1, Side_elem_position.rd1, Side_position.front) -> Array("B'", "R'", "B", "R", "B", "D", "B'", "D'"),
    (Side_elem_position.bd2, Side_elem_position.rd1, Side_position.front) -> Array("B2", "D", "B'", "D'", "B'", "R'", "B", "R"),

    // start side: right
    (Side_elem_position.fu1, Side_elem_position.fu1, Side_position.right) -> Array(""),
    (Side_elem_position.fu2, Side_elem_position.fu1, Side_position.right) -> Array("U", "L2", "U'", "L", "U", "L2", "U'", "L", "F'", "L'", "F"),
    (Side_elem_position.fd1, Side_elem_position.fu1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.fd2, Side_elem_position.fu1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.bu1, Side_elem_position.fu1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.bu2, Side_elem_position.fu1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.bd1, Side_elem_position.fu1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.bd2, Side_elem_position.fu1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.fl1, Side_elem_position.fu1, Side_position.right) -> Array("L", "U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fl2, Side_elem_position.fu1, Side_position.right) -> Array("L2", "F'", "L", "F", "L", "U", "L'", "U'"),
    (Side_elem_position.lu1, Side_elem_position.fu1, Side_position.right) -> Array("L'", "F'", "L", "F", "L", "U", "L'", "U'"),
    (Side_elem_position.lu2, Side_elem_position.fu1, Side_position.right) -> Array("L2", "U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.ld1, Side_elem_position.fu1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.ld2, Side_elem_position.fu1, Side_position.right) -> Array("L", "F'", "L", "F", "L", "U", "L'", "U'"),
    (Side_elem_position.br1, Side_elem_position.fu1, Side_position.right) -> Array("L'", "U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.br2, Side_elem_position.fu1, Side_position.right) -> Array("F'", "L", "F", "L", "U", "L'", "U'"),

    (Side_elem_position.fu1, Side_elem_position.fd1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fu2, Side_elem_position.fd1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fd1, Side_elem_position.fd1, Side_position.right) -> Array(""),
    (Side_elem_position.fd2, Side_elem_position.fd1, Side_position.right) -> Array("F", "L2", "F'", "L", "F", "L2", "F'", "L", "D'", "L'", "D"),
    (Side_elem_position.bu1, Side_elem_position.fd1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.bu2, Side_elem_position.fd1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.bd1, Side_elem_position.fd1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.bd2, Side_elem_position.fd1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.fl1, Side_elem_position.fd1, Side_position.right) -> Array("L2", "F", "L'", "F'", "L'", "D'", "L", "D"),
    (Side_elem_position.fl2, Side_elem_position.fd1, Side_position.right) -> Array("L'", "D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.lu1, Side_elem_position.fd1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.lu2, Side_elem_position.fd1, Side_position.right) -> Array("L'", "F", "L'", "F'", "L'", "D'", "L", "D"),
    (Side_elem_position.ld1, Side_elem_position.fd1, Side_position.right) -> Array("L", "F", "L'", "F'", "L'", "D'", "L", "D"),
    (Side_elem_position.ld2, Side_elem_position.fd1, Side_position.right) -> Array("L2", "D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.br1, Side_elem_position.fd1, Side_position.right) -> Array("F", "L'", "F'", "L'", "D'", "L", "D"),
    (Side_elem_position.br2, Side_elem_position.fd1, Side_position.right) -> Array("L", "D'", "L", "D", "L", "F", "L'", "F'"),

    (Side_elem_position.fu1, Side_elem_position.bu1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fu2, Side_elem_position.bu1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fd1, Side_elem_position.bu1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.fd2, Side_elem_position.bu1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.bu1, Side_elem_position.bu1, Side_position.right) -> Array(""),
    (Side_elem_position.bu2, Side_elem_position.bu1, Side_position.right) -> Array("B", "L2", "B'", "L", "B", "L2", "B'", "L", "U'", "L'", "U"),
    (Side_elem_position.bd1, Side_elem_position.bu1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.bd2, Side_elem_position.bu1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.fl1, Side_elem_position.bu1, Side_position.right) -> Array("L", "U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.fl2, Side_elem_position.bu1, Side_position.right) -> Array("B", "L'", "B'", "L'", "U'", "L", "U"),
    (Side_elem_position.lu1, Side_elem_position.bu1, Side_position.right) -> Array("L", "B", "L'", "B'", "L'", "U'", "L", "U"),
    (Side_elem_position.lu2, Side_elem_position.bu1, Side_position.right) -> Array("L2", "U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.ld1, Side_elem_position.bu1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.ld2, Side_elem_position.bu1, Side_position.right) -> Array("L'", "B", "L'", "B'", "L'", "U'", "L", "U"),
    (Side_elem_position.br1, Side_elem_position.bu1, Side_position.right) -> Array("L'", "U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.br2, Side_elem_position.bu1, Side_position.right) -> Array("L2", "B", "L'", "B'", "L'", "U'", "L", "U"),

    (Side_elem_position.fu1, Side_elem_position.bd1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fu2, Side_elem_position.bd1, Side_position.right) -> Array("U", "L'", "U'", "L'", "F'", "L", "F"),
    (Side_elem_position.fd1, Side_elem_position.bd1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.fd2, Side_elem_position.bd1, Side_position.right) -> Array("D'", "L", "D", "L", "F", "L'", "F'"),
    (Side_elem_position.bu1, Side_elem_position.bd1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.bu2, Side_elem_position.bd1, Side_position.right) -> Array("U'", "L", "U", "L", "B", "L'", "B'"),
    (Side_elem_position.bd1, Side_elem_position.bd1, Side_position.right) -> Array(""),
    (Side_elem_position.bd2, Side_elem_position.bd1, Side_position.right) -> Array("D", "L2", "D'", "L", "D", "L2", "D'", "L", "B'", "L'", "B"),
    (Side_elem_position.fl1, Side_elem_position.bd1, Side_position.right) -> Array("B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.fl2, Side_elem_position.bd1, Side_position.right) -> Array("L'", "D", "L'", "D'", "L'", "B'", "L", "B"),
    (Side_elem_position.lu1, Side_elem_position.bd1, Side_position.right) -> Array("D", "L'", "D'", "L'", "B'", "L", "B"),
    (Side_elem_position.lu2, Side_elem_position.bd1, Side_position.right) -> Array("L", "B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.ld1, Side_elem_position.bd1, Side_position.right) -> Array("L'", "B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.ld2, Side_elem_position.bd1, Side_position.right) -> Array("L2", "D", "L'", "D'", "L'", "B'", "L", "B"),
    (Side_elem_position.br1, Side_elem_position.bd1, Side_position.right) -> Array("L2", "B'", "L", "B", "L", "D", "L'", "D'"),
    (Side_elem_position.br2, Side_elem_position.bd1, Side_position.right) -> Array("L", "D", "L'", "D'", "L'", "B'", "L", "B"),

    // start side: back
    (Side_elem_position.lu1, Side_elem_position.lu1, Side_position.back) -> Array(""),
    (Side_elem_position.lu2, Side_elem_position.lu1, Side_position.back) -> Array("L", "F2", "L'", "F", "L", "F2", "L'", "F", "U'", "F'", "U"),
    (Side_elem_position.ld1, Side_elem_position.lu1, Side_position.back) -> Array("L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.ld2, Side_elem_position.lu1, Side_position.back) -> Array("L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.ru1, Side_elem_position.lu1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.ru2, Side_elem_position.lu1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.rd1, Side_elem_position.lu1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.rd2, Side_elem_position.lu1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.fu1, Side_elem_position.lu1, Side_position.back) -> Array("F", "L", "F'", "L'", "F'", "U'", "F", "U"),
    (Side_elem_position.fu2, Side_elem_position.lu1, Side_position.back) -> Array("F2", "U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.fl1, Side_elem_position.lu1, Side_position.back) -> Array("F2", "L", "F'", "L'", "F'", "U'", "F", "U"),
    (Side_elem_position.fl2, Side_elem_position.lu1, Side_position.back) -> Array("F'", "U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.fr1, Side_elem_position.lu1, Side_position.back) -> Array("F", "U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.fr2, Side_elem_position.lu1, Side_position.back) -> Array("L", "F'", "L'", "F'", "U'", "F", "U"),
    (Side_elem_position.fd1, Side_elem_position.lu1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.fd2, Side_elem_position.lu1, Side_position.back) -> Array("F'", "L", "F'", "L'", "F'", "U'", "F", "U"),

    (Side_elem_position.lu1, Side_elem_position.ld1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.lu2, Side_elem_position.ld1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.ld1, Side_elem_position.ld1, Side_position.back) -> Array(""),
    (Side_elem_position.ld2, Side_elem_position.ld1, Side_position.back) -> Array("D", "F2", "D'", "F", "D", "F2", "D'", "F", "L'", "F'", "L"),
    (Side_elem_position.ru1, Side_elem_position.ld1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.ru2, Side_elem_position.ld1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.rd1, Side_elem_position.ld1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.rd2, Side_elem_position.ld1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.fu1, Side_elem_position.ld1, Side_position.back) -> Array("D", "F'", "D'", "F'", "L'", "F", "L"),
    (Side_elem_position.fu2, Side_elem_position.ld1, Side_position.back) -> Array("F", "L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.fl1, Side_elem_position.ld1, Side_position.back) -> Array("F", "D", "F'", "D'", "F'", "L'", "F", "L"),
    (Side_elem_position.fl2, Side_elem_position.ld1, Side_position.back) -> Array("F2", "L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.fr1, Side_elem_position.ld1, Side_position.back) -> Array("L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.fr2, Side_elem_position.ld1, Side_position.back) -> Array("F'", "D", "F'", "D'", "F'", "L'", "F", "L"),
    (Side_elem_position.fd1, Side_elem_position.ld1, Side_position.back) -> Array("F'", "L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.fd2, Side_elem_position.ld1, Side_position.back) -> Array("F2", "D", "F'", "D'", "F'", "L'", "F", "L"),

    (Side_elem_position.lu1, Side_elem_position.ru1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.lu2, Side_elem_position.ru1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.ld1, Side_elem_position.ru1, Side_position.back) -> Array("L' ", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.ld2, Side_elem_position.ru1, Side_position.back) -> Array("L' ", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.ru1, Side_elem_position.ru1, Side_position.back) -> Array(""),
    (Side_elem_position.ru2, Side_elem_position.ru1, Side_position.back) -> Array("U", "F2", "U'", "F", "U", "F2", "U'", "F", "R'", "F'", "R"),
    (Side_elem_position.rd1, Side_elem_position.ru1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.rd2, Side_elem_position.ru1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.fu1, Side_elem_position.ru1, Side_position.back) -> Array("F'", "R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.fu2, Side_elem_position.ru1, Side_position.back) -> Array("F2", "U", "F'", "U'", "F'", "R'", "F", "R"),
    (Side_elem_position.fl1, Side_elem_position.ru1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.fl2, Side_elem_position.ru1, Side_position.back) -> Array("F'", "U", "F'", "U'", "F'", "R'", "F", "R"),
    (Side_elem_position.fr1, Side_elem_position.ru1, Side_position.back) -> Array("F", "U", "F'", "U'", "F'", "R'", "F", "R"),
    (Side_elem_position.fr2, Side_elem_position.ru1, Side_position.back) -> Array("F2", "R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.fd1, Side_elem_position.ru1, Side_position.back) -> Array("F", "R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.fd2, Side_elem_position.ru1, Side_position.back) -> Array("U", "F'", "U'", "F'", "R'", "F", "R"),

    (Side_elem_position.lu1, Side_elem_position.rd1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.lu2, Side_elem_position.rd1, Side_position.back) -> Array("U'", "F", "U", "F", "L", "F'", "L'"),
    (Side_elem_position.ld1, Side_elem_position.rd1, Side_position.back) -> Array("L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.ld2, Side_elem_position.rd1, Side_position.back) -> Array("L'", "F", "L", "F", "D", "F'", "D'"),
    (Side_elem_position.ru1, Side_elem_position.rd1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.ru2, Side_elem_position.rd1, Side_position.back) -> Array("R'", "F", "R", "F", "U", "F'", "U'"),
    (Side_elem_position.rd1, Side_elem_position.rd1, Side_position.back) -> Array(""),
    (Side_elem_position.rd2, Side_elem_position.rd1, Side_position.back) -> Array("R", "F2", "R'", "F", "R", "F2", "R'", "F", "D'", "F'", "D"),
    (Side_elem_position.fu1, Side_elem_position.rd1, Side_position.back) -> Array("D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.fu2, Side_elem_position.rd1, Side_position.back) -> Array("F'", "R", "F'", "R'", "F'", "D'", "F", "D"),
    (Side_elem_position.fl1, Side_elem_position.rd1, Side_position.back) -> Array("F", "D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.fl2, Side_elem_position.rd1, Side_position.back) -> Array("R", "F'", "R'", "F'", "D'", "F", "D"),
    (Side_elem_position.fr1, Side_elem_position.rd1, Side_position.back) -> Array("F2", "R", "F'", "R'", "F'", "D'", "F", "D"),
    (Side_elem_position.fr2, Side_elem_position.rd1, Side_position.back) -> Array("F'", "D'", "F", "D", "F", "R", "F'", "R'"),
    (Side_elem_position.fd1, Side_elem_position.rd1, Side_position.back) -> Array("F", "R", "F'", "R'", "F'", "D'", "F", "D"),
    (Side_elem_position.fd2, Side_elem_position.rd1, Side_position.back) -> Array("F2", "D'", "F", "D", "F", "R", "F'", "R'"),

    // start side: down
    (Side_elem_position.fl1, Side_elem_position.fl1, Side_position.down) -> Array(""),
    (Side_elem_position.fl2, Side_elem_position.fl1, Side_position.down) -> Array("F", "U2", "F'", "U", "F", "U2", "F'", "U", "L'", "U'", "L"),
    (Side_elem_position.fr1, Side_elem_position.fl1, Side_position.down) -> Array("R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.fr2, Side_elem_position.fl1, Side_position.down) -> Array("R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.bl1, Side_elem_position.fl1, Side_position.down) -> Array("L'", "U", "L", "U", "B", "U'", "B'"),
    (Side_elem_position.bl2, Side_elem_position.fl1, Side_position.down) -> Array("L'", "U", "L", "U", "B", "U'", "B'"),
    (Side_elem_position.br1, Side_elem_position.fl1, Side_position.down) -> Array("B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.br2, Side_elem_position.fl1, Side_position.down) -> Array("B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.fu1, Side_elem_position.fl1, Side_position.down) -> Array("U2", "F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fu2, Side_elem_position.fl1, Side_position.down) -> Array("U'", "L'", "U", "L", "U", "F", "U'", "F'"),
    (Side_elem_position.lu1, Side_elem_position.fl1, Side_position.down) -> Array("U", "F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.lu2, Side_elem_position.fl1, Side_position.down) -> Array("U2", "L'", "U", "L", "U", "F", "U'", "F'"),
    (Side_elem_position.ru1, Side_elem_position.fl1, Side_position.down) -> Array("U'", "F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.ru2, Side_elem_position.fl1, Side_position.down) -> Array("L'", "U", "L", "U", "F", "U'", "F'"),
    (Side_elem_position.bu1, Side_elem_position.fl1, Side_position.down) -> Array("F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.bu2, Side_elem_position.fl1, Side_position.down) -> Array("U", "L'", "U", "L", "U", "F", "U'", "F'"),

    (Side_elem_position.fl1, Side_elem_position.fr1, Side_position.down) -> Array("U2", "F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fl2, Side_elem_position.fr1, Side_position.down) -> Array("U2", "F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fr1, Side_elem_position.fr1, Side_position.down) -> Array(""),
    (Side_elem_position.fr2, Side_elem_position.fr1, Side_position.down) -> Array("R", "U2", "R'", "U", "R", "U2", "R'", "U", "F'", "U'", "F"),
    (Side_elem_position.bl1, Side_elem_position.fr1, Side_position.down) -> Array("B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.bl2, Side_elem_position.fr1, Side_position.down) -> Array("B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.br1, Side_elem_position.fr1, Side_position.down) -> Array("B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.br2, Side_elem_position.fr1, Side_position.down) -> Array("B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.fu1, Side_elem_position.fr1, Side_position.down) -> Array("U2", "F'", "U", "F", "U", "R", "U'", "R'"),
    (Side_elem_position.fu2, Side_elem_position.fr1, Side_position.down) -> Array("U", "R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.lu1, Side_elem_position.fr1, Side_position.down) -> Array("U", "F'", "U", "F", "U", "R", "U'", "R'"),
    (Side_elem_position.lu2, Side_elem_position.fr1, Side_position.down) -> Array("R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.ru1, Side_elem_position.fr1, Side_position.down) -> Array("U'", "F'", "U", "F", "U", "R", "U'", "R'"),
    (Side_elem_position.ru2, Side_elem_position.fr1, Side_position.down) -> Array("U2", "R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.bu1, Side_elem_position.fr1, Side_position.down) -> Array("F'", "U", "F", "U", "R", "U'", "R'"),
    (Side_elem_position.bu2, Side_elem_position.fr1, Side_position.down) -> Array("U'", "R", "U'", "R'", "U'", "F'", "U", "F"),

    (Side_elem_position.fl1, Side_elem_position.bl1, Side_position.down) -> Array("F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fl2, Side_elem_position.bl1, Side_position.down) -> Array("F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fr1, Side_elem_position.bl1, Side_position.down) -> Array("U'", "R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.fr2, Side_elem_position.bl1, Side_position.down) -> Array("U'", "R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.bl1, Side_elem_position.bl1, Side_position.down) -> Array(""),
    (Side_elem_position.bl2, Side_elem_position.bl1, Side_position.down) -> Array("B", "U2", "B'", "U", "B", "U2", "B'", "U", "R'", "U'", "R"),
    (Side_elem_position.br1, Side_elem_position.bl1, Side_position.down) -> Array("U", "L", "U'", "L'", "U'", "B'", "U", "B"),
    (Side_elem_position.br2, Side_elem_position.bl1, Side_position.down) -> Array("U", "L", "U'", "L'", "U'", "B'", "U", "B"),
    (Side_elem_position.fu1, Side_elem_position.bl1, Side_position.down) -> Array("B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.fu2, Side_elem_position.bl1, Side_position.down) -> Array("R'", "U", "R", "U", "B", "U'", "B'"),
    (Side_elem_position.lu1, Side_elem_position.bl1, Side_position.down) -> Array("U'", "B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.lu2, Side_elem_position.bl1, Side_position.down) -> Array("U'", "L'", "U", "L", "U", "B", "U'", "B'"),
    (Side_elem_position.ru1, Side_elem_position.bl1, Side_position.down) -> Array("U", "B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.ru2, Side_elem_position.bl1, Side_position.down) -> Array("U", "L'", "U", "L", "U", "B", "U'", "B'"),
    (Side_elem_position.bu1, Side_elem_position.bl1, Side_position.down) -> Array("U2", "B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.bu2, Side_elem_position.bl1, Side_position.down) -> Array("U2", "L'", "U", "L", "U", "B", "U'", "B'"),

    (Side_elem_position.fl1, Side_elem_position.br1, Side_position.down) -> Array("F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fl2, Side_elem_position.br1, Side_position.down) -> Array("F", "U'", "F'", "U'", "L'", "U", "L"),
    (Side_elem_position.fr1, Side_elem_position.br1, Side_position.down) -> Array("U'", "R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.fr2, Side_elem_position.br1, Side_position.down) -> Array("U'", "R", "U'", "R'", "U'", "F'", "U", "F"),
    (Side_elem_position.bl1, Side_elem_position.br1, Side_position.down) -> Array("U2", "B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.bl2, Side_elem_position.br1, Side_position.down) -> Array("U2", "B", "U'", "B'", "U'", "R'", "U", "R"),
    (Side_elem_position.br1, Side_elem_position.br1, Side_position.down) -> Array(""),
    (Side_elem_position.br2, Side_elem_position.br1, Side_position.down) -> Array("L", "U2", "L'", "U", "L", "U2", "L'", "U", "B'", "U'", "B"),
    (Side_elem_position.fu1, Side_elem_position.br1, Side_position.down) -> Array("U'", "L", "U'", "L'", "U'", "B'", "U", "B"),
    (Side_elem_position.fu2, Side_elem_position.br1, Side_position.down) -> Array("B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.lu1, Side_elem_position.br1, Side_position.down) -> Array("U2", "L", "U'", "L'", "U'", "B'", "U", "B"),
    (Side_elem_position.lu2, Side_elem_position.br1, Side_position.down) -> Array("U'", "B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.ru1, Side_elem_position.br1, Side_position.down) -> Array("L", "U'", "L'", "U'", "B'", "U", "B"),
    (Side_elem_position.ru2, Side_elem_position.br1, Side_position.down) -> Array("U", "B'", "U", "B", "U", "L", "U'", "L'"),
    (Side_elem_position.bu1, Side_elem_position.br1, Side_position.down) -> Array("U", "L", "U'", "L'", "U'", "B'", "U", "B"),
    (Side_elem_position.bu2, Side_elem_position.br1, Side_position.down) -> Array("U2", "B'", "U", "B", "U", "L", "U'", "L'")
  )
}
