/*
    Collection movies for F2L step
    (<current_position_angle_elem>, <current_position_side_elem>) -> <needed_movies>

    current_position_angle_elem => xxx(1,2,3)
    current_position_side_elem => xx(1, 2)

    !!! All combinations for start_side = down and front_side = front !!!
 */

package src

trait Collection_movies_for_F2L {
  val collectionMoviesForF2L = Map(
    (Angle_elem_position.fur1, Side_elem_position.bu1) -> Array("U'", "R", "U", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.fur1, Side_elem_position.bu2) -> Array("U'", "R", "U'", "R'", "U", "F'", "U'", "F"),
    (Angle_elem_position.fur1, Side_elem_position.lu1) -> Array("U'", "R", "U2", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.fur1, Side_elem_position.lu2) -> Array("F'", "U'", "F"),
    (Angle_elem_position.fur1, Side_elem_position.ru1) -> Array("U", "R", "U'", "R'"),
    (Angle_elem_position.fur1, Side_elem_position.ru2) -> Array("F", "U2", "F2", "U'", "F2", "U'", "F'"),
    (Angle_elem_position.fur1, Side_elem_position.fu1) -> Array("F'", "U", "F", "U2", "R", "U", "R'"),
    (Angle_elem_position.fur1, Side_elem_position.fu2) -> Array("U", "F'", "U", "F", "U'", "F'", "U'", "F"),
    (Angle_elem_position.fur1, Side_elem_position.fr1) -> Array("U'", "R", "U'", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.fur1, Side_elem_position.fr2) -> Array("U'", "R", "U", "R'", "U", "F'", "U'", "F"),

    (Angle_elem_position.fur2, Side_elem_position.bu1) -> Array("R", "U", "R'"),
    (Angle_elem_position.fur2, Side_elem_position.bu2) -> Array("U", "F'", "U2", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.fur2, Side_elem_position.lu1) -> Array("U'", "R", "U", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.fur2, Side_elem_position.lu2) -> Array("U", "F'", "U'", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.fur2, Side_elem_position.ru1) -> Array("U'", "R", "U'", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.fur2, Side_elem_position.ru2) -> Array("R", "U'", "R'", "U2", "F'", "U'", "F"),
    (Angle_elem_position.fur2, Side_elem_position.fu1) -> Array("R'", "U2", "R2", "U", "R2", "U", "R"),
    (Angle_elem_position.fur2, Side_elem_position.fu2) -> Array("F", "R'", "F'", "R"),
    (Angle_elem_position.fur2, Side_elem_position.fr1) -> Array("U'", "R", "U2", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.fur2, Side_elem_position.fr2) -> Array("U", "F'", "U'", "F", "U'", "R", "U", "R'"),

    (Angle_elem_position.fur3, Side_elem_position.bu1) -> Array("U", "R", "U2", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.fur3, Side_elem_position.bu2) -> Array("U2", "R", "U", "R'", "F'", "U'", "F"),
    (Angle_elem_position.fur3, Side_elem_position.lu1) -> Array("U2", "F'", "U'", "L", "F", "U", "F'"),
    (Angle_elem_position.fur3, Side_elem_position.lu2) -> Array("U'", "F'", "U2", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.fur3, Side_elem_position.ru1) -> Array("R", "U2", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.fur3, Side_elem_position.ru2) -> Array("F", "U", "R", "U'", "R'", "F'", "R", "U'", "R'"),
    (Angle_elem_position.fur3, Side_elem_position.fu1) -> Array("U2", "R2", "U2", "R'", "U'", "R", "U'", "R2"),
    (Angle_elem_position.fur3, Side_elem_position.fu2) -> Array("F'", "U2", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.fur3, Side_elem_position.fr1) -> Array("R", "U", "R'", "U'", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.fur3, Side_elem_position.fr2) -> Array("R", "U'", "R'", "U", "F'", "U", "F"),

    (Angle_elem_position.fdr1, Side_elem_position.bu1) -> Array("U", "R'", "F'", "R", "U", "R", "U'", "R'", "F"),
    (Angle_elem_position.fdr1, Side_elem_position.bu2) -> Array("U'", "R", "U'", "R'", "F", "R'", "F'", "R"),
    (Angle_elem_position.fdr1, Side_elem_position.lu1) -> Array("U2", "R'", "F'", "R", "U", "R", "U'", "R'", "F"),
    (Angle_elem_position.fdr1, Side_elem_position.lu2) -> Array("R", "U'", "R'", "F", "R'", "F'", "R"),
    (Angle_elem_position.fdr1, Side_elem_position.ru1) -> Array("R'", "F'", "R", "U", "R", "U'", "R'", "F"),
    (Angle_elem_position.fdr1, Side_elem_position.ru2) -> Array("U2", "R", "U'", "R'", "F", "R'", "F'", "R"),
    (Angle_elem_position.fdr1, Side_elem_position.fu1) -> Array("U'", "R'", "F'", "R", "U", "R", "U'", "R'", "F"),
    (Angle_elem_position.fdr1, Side_elem_position.fu2) -> Array("U", "R", "U'", "R'", "F", "R'", "F'", "R"),
    (Angle_elem_position.fdr1, Side_elem_position.fr1) -> Array(""), //OK
    (Angle_elem_position.fdr1, Side_elem_position.fr2) -> Array("R", "U'", "R'", "U", "F'", "U2", "F", "U2", "F'", "U", "F"),

    (Angle_elem_position.fdr2, Side_elem_position.bu1) -> Array("U", "R", "U'", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.fdr2, Side_elem_position.bu2) -> Array("U2", "F'", "U'", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.fdr2, Side_elem_position.lu1) -> Array("U2", "R", "U'", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.fdr2, Side_elem_position.lu2) -> Array("U'", "F'", "U'", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.fdr2, Side_elem_position.ru1) -> Array("R", "U'", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.fdr2, Side_elem_position.ru2) -> Array("U", "F'", "U'", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.fdr2, Side_elem_position.fu1) -> Array("U'", "R", "U'", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.fdr2, Side_elem_position.fu2) -> Array("F'", "U'", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.fdr2, Side_elem_position.fr1) -> Array("R", "U'", "R'", "U'", "R", "U", "R'", "U2", "R", "U'", "R'"),// ???
    (Angle_elem_position.fdr2, Side_elem_position.fr2) -> Array("R", "F", "U", "R", "U'", "R'", "F'", "U'", "R'"),

    (Angle_elem_position.fdr3, Side_elem_position.bu1) -> Array("U", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.fdr3, Side_elem_position.bu2) -> Array("U2", "F'", "U", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.fdr3, Side_elem_position.lu1) -> Array("U2", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.fdr3, Side_elem_position.lu2) -> Array("U'", "F'", "U", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.fdr3, Side_elem_position.ru1) -> Array("R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.fdr3, Side_elem_position.ru2) -> Array("U", "F'", "U", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.fdr3, Side_elem_position.fu1) -> Array("U'", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.fdr3, Side_elem_position.fu2) -> Array("F'", "U", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.fdr3, Side_elem_position.fr1) -> Array("R", "U2", "R", "U", "R'", "U", "R", "U2", "R2"),
    (Angle_elem_position.fdr3, Side_elem_position.fr2) -> Array("R", "B", "U2", "B'", "R'", "F'", "U'", "F"),

    (Angle_elem_position.ful1, Side_elem_position.bu1) -> Array("U2", "R", "U2", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.ful1, Side_elem_position.bu2) -> Array("U'", "F'", "U'", "F"),
    (Angle_elem_position.ful1, Side_elem_position.lu1) -> Array("U'", "F'", "U", "F", "U2", "R", "U", "R'"),
    (Angle_elem_position.ful1, Side_elem_position.lu2) -> Array("F'", "U", "F", "U'", "F'", "U'", "F"),
    (Angle_elem_position.ful1, Side_elem_position.ru1) -> Array("U2", "R", "U", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.ful1, Side_elem_position.ru2) -> Array("U2", "R", "U'", "R'", "U", "F'", "U'", "F"),
    (Angle_elem_position.ful1, Side_elem_position.fu1) -> Array("R", "U'", "R'"),
    (Angle_elem_position.ful1, Side_elem_position.fu2) -> Array("U'", "F", "U2", "F2", "U'", "F2", "U'", "F'"),
    (Angle_elem_position.ful1, Side_elem_position.fr1) -> Array("U2", "R", "U'", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.ful1, Side_elem_position.fr2) -> Array("U2", "R", "U", "R'", "U", "F'", "U'", "F"),

    (Angle_elem_position.ful2, Side_elem_position.bu1) -> Array("U2", "R", "U", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.ful2, Side_elem_position.bu2) -> Array("F'", "U'", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.ful2, Side_elem_position.lu1) -> Array("U'", "R'", "U2", "R2", "U", "R2", "U", "R"),
    (Angle_elem_position.ful2, Side_elem_position.lu2) -> Array("U'", "F", "R'", "F'", "R"),
    (Angle_elem_position.ful2, Side_elem_position.ru1) -> Array("U'", "R", "U", "R'"),
    (Angle_elem_position.ful2, Side_elem_position.ru2) -> Array("F'", "U2", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.ful2, Side_elem_position.fu1) -> Array("U2", "R", "U'", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.ful2, Side_elem_position.fu2) -> Array("U'", "R", "U'", "R'", "U2", "F'", "U'", "F"),
    (Angle_elem_position.ful2, Side_elem_position.fr1) -> Array("U2", "R", "U2", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.ful2, Side_elem_position.fr2) -> Array("F'", "U'", "F", "U'", "R", "U", "R'"),

    (Angle_elem_position.ful3, Side_elem_position.bu1) -> Array("U", "F'", "U'", "L", "F", "U", "F'"),
    (Angle_elem_position.ful3, Side_elem_position.bu2) -> Array("U2", "F'", "U2", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.ful3, Side_elem_position.lu1) -> Array("U", "R2", "U2", "R'", "U'", "R", "U'", "R2"),
    (Angle_elem_position.ful3, Side_elem_position.lu2) -> Array("U'", "F'", "U2", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.ful3, Side_elem_position.ru1) -> Array("R", "U2", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.ful3, Side_elem_position.ru2) -> Array("U", "R", "U", "R'", "F'", "U'", "F"),
    (Angle_elem_position.ful3, Side_elem_position.fu1) -> Array("U'", "R", "U2", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.ful3, Side_elem_position.fu2) -> Array("U'", "F", "U", "R", "U'", "R'", "F'", "R", "U'", "R'"),
    (Angle_elem_position.ful3, Side_elem_position.fr1) -> Array("U'", "R", "U", "R'", "U'", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.ful3, Side_elem_position.fr2) -> Array("U'", "R", "U'", "R'", "U", "F'", "U", "F"),

    (Angle_elem_position.bur1, Side_elem_position.bu1) -> Array("U2", "F'", "U", "F", "U2", "R", "U", "R'"),
    (Angle_elem_position.bur1, Side_elem_position.bu2) -> Array("U'", "F'", "U", "F", "U'", "F'", "U'", "F"),
    (Angle_elem_position.bur1, Side_elem_position.lu1) -> Array("U'", "R", "U'", "R'"),
    (Angle_elem_position.bur1, Side_elem_position.lu2) -> Array("U2", "F", "U2", "F2", "U'", "F2", "U'", "F'"),
    (Angle_elem_position.bur1, Side_elem_position.ru1) -> Array("U", "R", "U2", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.bur1, Side_elem_position.ru2) -> Array("U2", "F'", "U'", "F"),
    (Angle_elem_position.bur1, Side_elem_position.fu1) -> Array("U", "R", "U", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.bur1, Side_elem_position.fu2) -> Array("U", "R", "U'", "R'", "U", "F'", "U'", "F"),
    (Angle_elem_position.bur1, Side_elem_position.fr1) -> Array("U", "R", "U'", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.bur1, Side_elem_position.fr2) -> Array("U", "R", "U", "R'", "U", "F'", "U'", "F"),

    (Angle_elem_position.bur2, Side_elem_position.bu1) -> Array("R2", "U2", "R'", "U'", "R", "U'", "R2"),
    (Angle_elem_position.bur2, Side_elem_position.bu2) -> Array("U2", "F'", "U2", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.bur2, Side_elem_position.lu1) -> Array("U2", "R", "U2", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.bur2, Side_elem_position.lu2) -> Array("U2", "F", "U", "R", "U'", "R'", "F'", "R", "U'", "R'"),
    (Angle_elem_position.bur2, Side_elem_position.ru1) -> Array("F'", "U'", "L", "F", "U", "F'"),
    (Angle_elem_position.bur2, Side_elem_position.ru2) -> Array("U", "F'", "U2", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.bur2, Side_elem_position.fu1) -> Array("U'", "R", "U2", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.bur2, Side_elem_position.fu2) -> Array("R", "U", "R'", "F'", "U'", "F"),
    (Angle_elem_position.bur2, Side_elem_position.fr1) -> Array("U2", "R", "U", "R'", "U'", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.bur2, Side_elem_position.fr2) -> Array("U2", "R", "U'", "R'", "U", "F'", "U", "F"),

    (Angle_elem_position.bur3, Side_elem_position.bu1) -> Array("U2", "R'", "U2", "R2", "U", "R2", "U", "R"),
    (Angle_elem_position.bur3, Side_elem_position.bu2) -> Array("U2", "F", "R'", "F'", "R"),
    (Angle_elem_position.bur3, Side_elem_position.lu1) -> Array("U", "R", "U'", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.bur3, Side_elem_position.lu2) -> Array("U2", "R", "U'", "R'", "U2", "F'", "U'", "F"),
    (Angle_elem_position.bur3, Side_elem_position.ru1) -> Array("U", "R", "U", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.bur3, Side_elem_position.ru2) -> Array("U'", "F'", "U'", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.bur3, Side_elem_position.fu1) -> Array("U2", "R", "U", "R'"),
    (Angle_elem_position.bur3, Side_elem_position.fu2) -> Array("U'", "F'", "U2", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.bur3, Side_elem_position.fr1) -> Array("U", "R", "U2", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.bur3, Side_elem_position.fr2) -> Array("U'", "F'", "U'", "F", "U'", "R", "U", "R'"),

    (Angle_elem_position.bul1, Side_elem_position.bu1) -> Array("U2", "R", "U'", "R'"),
    (Angle_elem_position.bul1, Side_elem_position.bu2) -> Array("U", "F", "U2", "F2", "U'", "F2", "U'", "F'"),
    (Angle_elem_position.bul1, Side_elem_position.lu1) -> Array("R", "U", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.bul1, Side_elem_position.lu2) -> Array("R", "U'", "R'", "U", "F'", "U'", "F"),
    (Angle_elem_position.bul1, Side_elem_position.ru1) -> Array("U", "F'", "U", "F", "U2", "R", "U", "R'"),
    (Angle_elem_position.bul1, Side_elem_position.ru2) -> Array("U2", "F'", "U", "F", "U'", "F'", "U'", "F"),
    (Angle_elem_position.bul1, Side_elem_position.fu1) -> Array("R", "U2", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.bul1, Side_elem_position.fu2) -> Array("U", "F'", "U'", "F"),
    (Angle_elem_position.bul1, Side_elem_position.fr1) -> Array("R", "U'", "R'", "U2", "R", "U'", "R'"),
    (Angle_elem_position.bul1, Side_elem_position.fr2) -> Array("R", "U", "R'", "U", "F'", "U'", "F"),

    (Angle_elem_position.bul2, Side_elem_position.bu1) -> Array("R", "U'", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.bul2, Side_elem_position.bu2) -> Array("U", "R", "U'", "R'", "U2", "F'", "U'", "F"),
    (Angle_elem_position.bul2, Side_elem_position.lu1) -> Array("U", "R", "U", "R'"),
    (Angle_elem_position.bul2, Side_elem_position.lu2) -> Array("U2", "F'", "U2", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.bul2, Side_elem_position.ru1) -> Array("U", "R'", "U2", "R2", "U", "R2", "U", "R"),
    (Angle_elem_position.bul2, Side_elem_position.ru2) -> Array("U", "F", "R'", "F'", "R"),
    (Angle_elem_position.bul2, Side_elem_position.fu1) -> Array("R", "U", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.bul2, Side_elem_position.fu2) -> Array("U2", "F'", "U'", "F", "U", "F'", "U2", "F"),
    (Angle_elem_position.bul2, Side_elem_position.fr1) -> Array("R", "U2", "R'", "U", "R", "U", "R'"),
    (Angle_elem_position.bul2, Side_elem_position.fr2) -> Array("U2", "F'", "U'", "F", "U'", "R", "U", "R'"),

    (Angle_elem_position.bul3, Side_elem_position.bu1) -> Array("U", "R", "U2", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.bul3, Side_elem_position.bu2) -> Array("U", "F", "U", "R", "U'", "R'", "F'", "R", "U'", "R'"),
    (Angle_elem_position.bul3, Side_elem_position.lu1) -> Array("U2", "R", "U2", "R'", "U", "R", "U'", "R'"),
    (Angle_elem_position.bul3, Side_elem_position.lu2) -> Array("U'", "R", "U", "R'", "F'", "U'", "F"),
    (Angle_elem_position.bul3, Side_elem_position.ru1) -> Array("U'", "R2", "U2", "R'", "U'", "R", "U'", "R2"),
    (Angle_elem_position.bul3, Side_elem_position.ru2) -> Array("U", "F'", "U2", "F", "U", "F'", "U'", "F"),
    (Angle_elem_position.bul3, Side_elem_position.fu1) -> Array("U'", "F'", "U'", "L", "F", "U", "F'"),
    (Angle_elem_position.bul3, Side_elem_position.fu2) -> Array("F'", "U2", "F", "U'", "F'", "U", "F"),
    (Angle_elem_position.bul3, Side_elem_position.fr1) -> Array("U", "R", "U", "R'", "U'", "R", "U", "R'", "U'", "R", "U", "R'"),
    (Angle_elem_position.bul3, Side_elem_position.fr2) -> Array("U", "R", "U'", "R'", "U", "F'", "U", "F"),
  )
}
