package src

trait Collection_angle_movies_full_side_first {
  val collectionAngleMoviesFullSideFirst = Map(
    // start_side: up
    (Angle_elem_position.ful1, Angle_elem_position.ful1, Side_position.up) -> Array(""),
    (Angle_elem_position.ful2, Angle_elem_position.ful1, Side_position.up) -> Array("L", "D", "L'", "D'", "L", "D", "L'"),
    (Angle_elem_position.ful3, Angle_elem_position.ful1, Side_position.up) -> Array("L", "D'", "L'", "D", "L", "D'", "L'"),
    (Angle_elem_position.fur1, Angle_elem_position.ful1, Side_position.up) -> Array("R'", "D'", "L", "D", "L'", "R"),
    (Angle_elem_position.fur2, Angle_elem_position.ful1, Side_position.up) -> Array("F", "D", "F2", "D2", "F"),
    (Angle_elem_position.fur3, Angle_elem_position.ful1, Side_position.up) -> Array("R'", "D'", "F'", "D'", "F", "R"),
    (Angle_elem_position.fdl1, Angle_elem_position.ful1, Side_position.up) -> Array("F'", "D", "F", "L", "D2", "L'"),
    (Angle_elem_position.fdl2, Angle_elem_position.ful1, Side_position.up) -> Array("F'", "D'", "F"),
    (Angle_elem_position.fdl3, Angle_elem_position.ful1, Side_position.up) -> Array("L", "D'", "L'", "F'", "D2", "F"),
    (Angle_elem_position.fdr1, Angle_elem_position.ful1, Side_position.up) -> Array("D'", "L", "D", "L'"),
    (Angle_elem_position.fdr2, Angle_elem_position.ful1, Side_position.up) -> Array("L", "D'", "L'"),
    (Angle_elem_position.fdr3, Angle_elem_position.ful1, Side_position.up) -> Array("D", "F'", "D", "F", "L", "D2", "L'"),
    (Angle_elem_position.bul1, Angle_elem_position.ful1, Side_position.up) -> Array("B'", "F'", "D2", "B", "F"),
    (Angle_elem_position.bul2, Angle_elem_position.ful1, Side_position.up) -> Array("R", "F'", "D2", "F", "R'"),
    (Angle_elem_position.bul3, Angle_elem_position.ful1, Side_position.up) -> Array("B'", "L", "D2", "L'", "B"),
    (Angle_elem_position.bur1, Angle_elem_position.ful1, Side_position.up) -> Array("B'", "L", "B2", "D", "B'", "L'"),
    (Angle_elem_position.bur2, Angle_elem_position.ful1, Side_position.up) -> Array("L'", "D'", "L2", "D2", "L'"),
    (Angle_elem_position.bur3, Angle_elem_position.ful1, Side_position.up) -> Array("B", "F'", "D", "F", "B'"),
    (Angle_elem_position.bdl1, Angle_elem_position.ful1, Side_position.up) -> Array("D2", "L", "D", "L'"),
    (Angle_elem_position.bdl2, Angle_elem_position.ful1, Side_position.up) -> Array("L", "D2", "L'"),
    (Angle_elem_position.bdl3, Angle_elem_position.ful1, Side_position.up) -> Array("D2", "F'", "D", "F", "L", "D2", "L'"),
    (Angle_elem_position.bdr1, Angle_elem_position.ful1, Side_position.up) -> Array("D2", "L", "D'", "L'"),
    (Angle_elem_position.bdr2, Angle_elem_position.ful1, Side_position.up) -> Array("D", "L", "D", "L'"),
    (Angle_elem_position.bdr3, Angle_elem_position.ful1, Side_position.up) -> Array("D'", "F'", "D", "F", "L", "D2", "L'"),

    (Angle_elem_position.ful1, Angle_elem_position.fur1, Side_position.up) -> Array("L", "D", "R'", "D'", "R", "L'"),
    (Angle_elem_position.ful2, Angle_elem_position.fur1, Side_position.up) -> Array("L", "R'", "D", "R", "L'"),
    (Angle_elem_position.ful3, Angle_elem_position.fur1, Side_position.up) -> Array("F'", "D'", "F2", "D2", "F'"),
    (Angle_elem_position.fur1, Angle_elem_position.fur1, Side_position.up) -> Array(""),
    (Angle_elem_position.fur2, Angle_elem_position.fur1, Side_position.up) -> Array("R'", "D", "R", "D'", "R'", "D", "R"),
    (Angle_elem_position.fur3, Angle_elem_position.fur1, Side_position.up) -> Array("R'", "D2", "R'", "U'", "B", "U", "R2"),
    (Angle_elem_position.fdl1, Angle_elem_position.fur1, Side_position.up) -> Array("R'", "D", "R"),
    (Angle_elem_position.fdl2, Angle_elem_position.fur1, Side_position.up) -> Array("D", "R'", "D'", "R"),
    (Angle_elem_position.fdl3, Angle_elem_position.fur1, Side_position.up) -> Array("R'", "D2", "R", "D'", "R'", "D", "R"),
    (Angle_elem_position.fdr1, Angle_elem_position.fur1, Side_position.up) -> Array("D'", "R'", "D", "R"),
    (Angle_elem_position.fdr2, Angle_elem_position.fur1, Side_position.up) -> Array("R'", "D'", "R"),
    (Angle_elem_position.fdr3, Angle_elem_position.fur1, Side_position.up) -> Array("F", "D'", "F'", "R'", "D2", "R"),
    (Angle_elem_position.bul1, Angle_elem_position.fur1, Side_position.up) -> Array("B'", "D'", "F", "D", "F'", "B"),
    (Angle_elem_position.bul2, Angle_elem_position.fur1, Side_position.up) -> Array("R", "D", "R2", "D2", "R"),
    (Angle_elem_position.bul3, Angle_elem_position.fur1, Side_position.up) -> Array("B'", "F", "D'", "F'", "B"),
    (Angle_elem_position.bur1, Angle_elem_position.fur1, Side_position.up) -> Array("B", "F", "D2", "D'", "B'"),
    (Angle_elem_position.bur2, Angle_elem_position.fur1, Side_position.up) -> Array("B", "D'", "B'", "F", "D2", "F'"),
    (Angle_elem_position.bur3, Angle_elem_position.fur1, Side_position.up) -> Array("B", "R'", "D2", "R", "B'"),
    (Angle_elem_position.bdl1, Angle_elem_position.fur1, Side_position.up) -> Array("D", "R'", "D2", "R"),
    (Angle_elem_position.bdl2, Angle_elem_position.fur1, Side_position.up) -> Array("D'", "R'", "D'", "R"),
    (Angle_elem_position.bdl3, Angle_elem_position.fur1, Side_position.up) -> Array("R", "D'", "R2", "D", "R"),
    (Angle_elem_position.bdr1, Angle_elem_position.fur1, Side_position.up) -> Array("D2", "R'", "D'", "R"),
    (Angle_elem_position.bdr2, Angle_elem_position.fur1, Side_position.up) -> Array("R'", "D2", "R"),
    (Angle_elem_position.bdr3, Angle_elem_position.fur1, Side_position.up) -> Array("D2", "F", "D'", "F'", "R'", "D2", "R"),

    (Angle_elem_position.ful1, Angle_elem_position.bul1, Side_position.up) -> Array("F'", "B'", "D2", "B", "F"),
    (Angle_elem_position.ful2, Angle_elem_position.bul1, Side_position.up) -> Array("F'", "D", "F", "B'", "D2", "B"),
    (Angle_elem_position.ful3, Angle_elem_position.bul1, Side_position.up) -> Array("F'", "R", "D2", "R'", "F"),
    (Angle_elem_position.fur1, Angle_elem_position.bul1, Side_position.up) -> Array("F", "D2", "F'", "R", "D'", "R'"),
    (Angle_elem_position.fur2, Angle_elem_position.bul1, Side_position.up) -> Array("F", "B'", "D", "B", "F'"),
    (Angle_elem_position.fur3, Angle_elem_position.bul1, Side_position.up) -> Array("R'", "D'", "R2", "D2", "R'"),
    (Angle_elem_position.fdl1, Angle_elem_position.bul1, Side_position.up) -> Array("B'", "D2", "B"),
    (Angle_elem_position.fdl2, Angle_elem_position.bul1, Side_position.up) -> Array("R", "D2", "R'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bul1, Side_position.up) -> Array("D2", "R", "D'", "R'", "B'", "D2", "B"),
    (Angle_elem_position.fdr1, Angle_elem_position.bul1, Side_position.up) -> Array("B'", "D", "B"),
    (Angle_elem_position.fdr2, Angle_elem_position.bul1, Side_position.up) -> Array("D'", "R", "D2", "R'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bul1, Side_position.up) -> Array("D", "R", "D'", "R'", "B'", "D2", "B"),
    (Angle_elem_position.bul1, Angle_elem_position.bul1, Side_position.up) -> Array(""),
    (Angle_elem_position.bul2, Angle_elem_position.bul1, Side_position.up) -> Array("R", "D2", "R'", "B'", "D2", "B"),
    (Angle_elem_position.bul3, Angle_elem_position.bul1, Side_position.up) -> Array("B'", "D2", "B", "R", "D2", "R'"),
    (Angle_elem_position.bur1, Angle_elem_position.bul1, Side_position.up) -> Array("L'", "D2", "L", "B'", "D", "B"),
    (Angle_elem_position.bur2, Angle_elem_position.bul1, Side_position.up) -> Array("L'", "R", "D'", "R'", "L"),
    (Angle_elem_position.bur3, Angle_elem_position.bul1, Side_position.up) -> Array("B", "D2", "B2", "D", "B'"),
    (Angle_elem_position.bdl1, Angle_elem_position.bul1, Side_position.up) -> Array("R", "D", "R'"),
    (Angle_elem_position.bdl2, Angle_elem_position.bul1, Side_position.up) -> Array("D", "R", "D'", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bul1, Side_position.up) -> Array("R", "D'", "R'", "B'", "D2", "B"),
    (Angle_elem_position.bdr1, Angle_elem_position.bul1, Side_position.up) -> Array("R", "D'", "R'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bul1, Side_position.up) -> Array("D", "B'", "D2", "B"),
    (Angle_elem_position.bdr3, Angle_elem_position.bul1, Side_position.up) -> Array("D'", "R", "D'", "R'", "B'", "D2", "B"),

    (Angle_elem_position.ful1, Angle_elem_position.bur1, Side_position.up) -> Array("F'", "D2", "F", "L'", "D", "L"),
    (Angle_elem_position.ful2, Angle_elem_position.bur1, Side_position.up) -> Array("L", "D2", "L2", "D", "L"),
    (Angle_elem_position.ful3, Angle_elem_position.bur1, Side_position.up) -> Array("B", "F'", "D'", "F", "B'"),
    (Angle_elem_position.fur1, Angle_elem_position.bur1, Side_position.up) -> Array("F", "B", "D2", "B'", "F'"),
    (Angle_elem_position.fur2, Angle_elem_position.bur1, Side_position.up) -> Array("F", "L'", "D2", "L", "F'"),
    (Angle_elem_position.fur3, Angle_elem_position.bur1, Side_position.up) -> Array("R'", "B", "D2", "B'", "R"),
    (Angle_elem_position.fdl1, Angle_elem_position.bur1, Side_position.up) -> Array("D", "L'", "D2", "L"),
    (Angle_elem_position.fdl2, Angle_elem_position.bur1, Side_position.up) -> Array("B", "D'", "B'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bur1, Side_position.up) -> Array("D'", "L'", "D", "L", "B", "D2", "B'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bur1, Side_position.up) -> Array("L'", "D2", "L"),
    (Angle_elem_position.fdr2, Angle_elem_position.bur1, Side_position.up) -> Array("B", "D2", "B'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bur1, Side_position.up) -> Array("D2", "L'", "D", "L", "B", "D2", "B'"),
    (Angle_elem_position.bul1, Angle_elem_position.bur1, Side_position.up) -> Array("R", "D2", "R'", "B", "D'", "B'"),
    (Angle_elem_position.bul2, Angle_elem_position.bur1, Side_position.up) -> Array("R", "L'", "D", "L", "R'"),
    (Angle_elem_position.bul3, Angle_elem_position.bur1, Side_position.up) -> Array("B'", "D'", "B2", "D2", "B'"),
    (Angle_elem_position.bur1, Angle_elem_position.bur1, Side_position.up) -> Array(""),
    (Angle_elem_position.bur2, Angle_elem_position.bur1, Side_position.up) -> Array("B", "D'", "B'", "D", "B", "D'", "B'"),
    (Angle_elem_position.bur3, Angle_elem_position.bur1, Side_position.up) -> Array("B", "D'", "B'", "L'", "D", "L"),
    (Angle_elem_position.bdl1, Angle_elem_position.bur1, Side_position.up) -> Array("L'", "D", "L"),
    (Angle_elem_position.bdl2, Angle_elem_position.bur1, Side_position.up) -> Array("D'", "B", "D2", "B'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bur1, Side_position.up) -> Array("D", "B", "D'", "B'", "L'", "D2", "L"),
    (Angle_elem_position.bdr1, Angle_elem_position.bur1, Side_position.up) -> Array("D", "B", "D'", "B'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bur1, Side_position.up) -> Array("D'", "L'", "D", "L"),
    (Angle_elem_position.bdr3, Angle_elem_position.bur1, Side_position.up) -> Array("B", "D'", "B'", "L'", "D2", "L"),

    // start_side: left
    (Angle_elem_position.ful1, Angle_elem_position.ful1, Side_position.left) -> Array(""),
    (Angle_elem_position.ful2, Angle_elem_position.ful1, Side_position.left) -> Array("F", "R2", "F'", "U'", "R2", "U"),
    (Angle_elem_position.ful3, Angle_elem_position.ful1, Side_position.left) -> Array("F", "R'", "F'", "U'", "R'", "U"),
    (Angle_elem_position.fur1, Angle_elem_position.ful1, Side_position.left) -> Array("F", "R", "F'"),
    (Angle_elem_position.fur2, Angle_elem_position.ful1, Side_position.left) -> Array("F", "R'", "F'", "U'", "R2", "U"),
    (Angle_elem_position.fur3, Angle_elem_position.ful1, Side_position.left) -> Array("U'", "R'", "U"),
    (Angle_elem_position.fdl1, Angle_elem_position.ful1, Side_position.left) -> Array("U'", "D", "R", "D'", "U"),
    (Angle_elem_position.fdl2, Angle_elem_position.ful1, Side_position.left) -> Array("F'", "R'", "F", "U'", "R2", "U"),
    (Angle_elem_position.fdl3, Angle_elem_position.ful1, Side_position.left) -> Array("F'", "R'", "F2", "R2", "F'"),
    (Angle_elem_position.fdr1, Angle_elem_position.ful1, Side_position.left) -> Array("U'", "R", "U"),
    (Angle_elem_position.fdr2, Angle_elem_position.ful1, Side_position.left) -> Array("R'", "F", "R2", "F'"),
    (Angle_elem_position.fdr3, Angle_elem_position.ful1, Side_position.left) -> Array("R", "U'", "R", "U", "F", "R2", "F'"),
    (Angle_elem_position.bul1, Angle_elem_position.ful1, Side_position.left) -> Array("R'", "U'", "R", "U", "F", "R2", "F'"),
    (Angle_elem_position.bul2, Angle_elem_position.ful1, Side_position.left) -> Array("R", "F", "R2", "F'"),
    (Angle_elem_position.bul3, Angle_elem_position.ful1, Side_position.left) -> Array("R", "U'", "R2", "U"),
    (Angle_elem_position.bur1, Angle_elem_position.ful1, Side_position.left) -> Array("U", "R'", "U'", "F", "R'", "F'"),
    (Angle_elem_position.bur2, Angle_elem_position.ful1, Side_position.left) -> Array("U", "R", "U2", "R2", "U"),
    (Angle_elem_position.bur3, Angle_elem_position.ful1, Side_position.left) -> Array("U", "R", "U'", "F", "R2", "F'"),
    (Angle_elem_position.bdl1, Angle_elem_position.ful1, Side_position.left) -> Array("F", "R2", "F'"),
    (Angle_elem_position.bdl2, Angle_elem_position.ful1, Side_position.left) -> Array("R2", "U'", "R", "U", "F", "R2", "F'"),
    (Angle_elem_position.bdl3, Angle_elem_position.ful1, Side_position.left) -> Array("U'", "R2", "U"),
    (Angle_elem_position.bdr1, Angle_elem_position.ful1, Side_position.left) -> Array("B", "F", "R2", "F'", "B'"),
    (Angle_elem_position.bdr2, Angle_elem_position.ful1, Side_position.left) -> Array("D'", "F", "R2", "F'", "D"),
    (Angle_elem_position.bdr3, Angle_elem_position.ful1, Side_position.left) -> Array("D'", "U'", "R2", "U", "D"),

    (Angle_elem_position.ful1, Angle_elem_position.bur1, Side_position.left) -> Array("F", "B'", "R", "B", "F'"),
    (Angle_elem_position.ful2, Angle_elem_position.bur1, Side_position.left) -> Array("F", "R'", "F'", "R'", "U", "R2", "U'"),
    (Angle_elem_position.ful3, Angle_elem_position.bur1, Side_position.left) -> Array("F", "R2", "F'", "U", "R2", "U'"),
    (Angle_elem_position.fur1, Angle_elem_position.bur1, Side_position.left) -> Array("R", "U", "R'", "U'", "B'", "R2", "B"),
    (Angle_elem_position.fur2, Angle_elem_position.bur1, Side_position.left) -> Array("R'", "U", "R2", "U'"),
    (Angle_elem_position.fur3, Angle_elem_position.bur1, Side_position.left) -> Array("B'", "R", "B"),
    (Angle_elem_position.fdl1, Angle_elem_position.bur1, Side_position.left) -> Array("F'", "U", "R2", "U'", "F"),
    (Angle_elem_position.fdl2, Angle_elem_position.bur1, Side_position.left) -> Array("D", "B'", "R2", "B", "D'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bur1, Side_position.left) -> Array("D", "U", "R2", "U'", "D'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bur1, Side_position.left) -> Array("R2", "U", "R'", "U'", "B'", "R2", "B"),
    (Angle_elem_position.fdr2, Angle_elem_position.bur1, Side_position.left) -> Array("B'", "R2", "B"),
    (Angle_elem_position.fdr3, Angle_elem_position.bur1, Side_position.left) -> Array("U", "R2", "U'"),
    (Angle_elem_position.bul1, Angle_elem_position.bur1, Side_position.left) -> Array("R2", "U", "R2", "U'"),
    (Angle_elem_position.bul2, Angle_elem_position.bur1, Side_position.left) -> Array("U", "R'", "U'", "B'", "R2", "B"),
    (Angle_elem_position.bul3, Angle_elem_position.bur1, Side_position.left) -> Array("R'", "B'", "R", "B"),
    (Angle_elem_position.bur1, Angle_elem_position.bur1, Side_position.left) -> Array(""),
    (Angle_elem_position.bur2, Angle_elem_position.bur1, Side_position.left) -> Array("B'", "R2", "B", "U", "R2", "U'"),
    (Angle_elem_position.bur3, Angle_elem_position.bur1, Side_position.left) -> Array("B'", "R", "B", "R'", "B'", "R", "B"),
    (Angle_elem_position.bdl1, Angle_elem_position.bur1, Side_position.left) -> Array("R", "B'", "R2", "B"),
    (Angle_elem_position.bdl2, Angle_elem_position.bur1, Side_position.left) -> Array("U", "R'", "U'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bur1, Side_position.left) -> Array("R'", "B'", "R", "B", "U", "R2", "U'"),
    (Angle_elem_position.bdr1, Angle_elem_position.bur1, Side_position.left) -> Array("D'", "U", "R'", "U'", "D"),
    (Angle_elem_position.bdr2, Angle_elem_position.bur1, Side_position.left) -> Array("D", "B'", "D2", "R'", "B", "D"),
    (Angle_elem_position.bdr3, Angle_elem_position.bur1, Side_position.left) -> Array("B ", "R", "B2", "R2", "B"),

    (Angle_elem_position.ful1, Angle_elem_position.fdl1, Side_position.left) -> Array("U'", "D", "R'", "D'", "U"),
    (Angle_elem_position.ful2, Angle_elem_position.fdl1, Side_position.left) -> Array("F", "R", "F'", "D", "R2", "D'"),
    (Angle_elem_position.ful3, Angle_elem_position.fdl1, Side_position.left) -> Array("F", "R", "F2", "R2", "F"),
    (Angle_elem_position.fur1, Angle_elem_position.fdl1, Side_position.left) -> Array("D", "R'", "D'"),
    (Angle_elem_position.fur2, Angle_elem_position.fdl1, Side_position.left) -> Array("R", "F'", "R2", "F"),
    (Angle_elem_position.fur3, Angle_elem_position.fdl1, Side_position.left) -> Array("R'", "F'", "R", "F", "D", "R2", "D'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fdl1, Side_position.left) -> Array(""),
    (Angle_elem_position.fdl2, Angle_elem_position.fdl1, Side_position.left) -> Array("F'", "R2", "F", "D", "R2", "D'"),
    (Angle_elem_position.fdl3, Angle_elem_position.fdl1, Side_position.left) -> Array("D", "R2", "D'", "F'", "R2", "F"),
    (Angle_elem_position.fdr1, Angle_elem_position.fdl1, Side_position.left) -> Array("R2", "D", "R2", "D'"),
    (Angle_elem_position.fdr2, Angle_elem_position.fdl1, Side_position.left) -> Array("D", "R'", "D'", "F'", "R2", "F"),
    (Angle_elem_position.fdr3, Angle_elem_position.fdl1, Side_position.left) -> Array("R'", "F'", "R", "F"),
    (Angle_elem_position.bul1, Angle_elem_position.fdl1, Side_position.left) -> Array("F'", "R2", "F"),
    (Angle_elem_position.bul2, Angle_elem_position.fdl1, Side_position.left) -> Array("R2", "F'", "R", "F", "D", "R2", "D'"),
    (Angle_elem_position.bul3, Angle_elem_position.fdl1, Side_position.left) -> Array("D", "R2", "D'"),
    (Angle_elem_position.bur1, Angle_elem_position.fdl1, Side_position.left) -> Array("U", "F'", "R2", "F", "U'"),
    (Angle_elem_position.bur2, Angle_elem_position.fdl1, Side_position.left) -> Array("U", "D", "R2", "D'", "U'"),
    (Angle_elem_position.bur3, Angle_elem_position.fdl1, Side_position.left) -> Array("B'", "D", "R2", "D'", "B"),
    (Angle_elem_position.bdl1, Angle_elem_position.fdl1, Side_position.left) -> Array("R", "F'", "R", "F", "D", "R2", "D'"),
    (Angle_elem_position.bdl2, Angle_elem_position.fdl1, Side_position.left) -> Array("F'", "R", "F"),
    (Angle_elem_position.bdl3, Angle_elem_position.fdl1, Side_position.left) -> Array("R'", "D", "R2", "D'"),
    (Angle_elem_position.bdr1, Angle_elem_position.fdl1, Side_position.left) -> Array("B", "R2", "B'", "D", "R'", "D'"),
    (Angle_elem_position.bdr2, Angle_elem_position.fdl1, Side_position.left) -> Array("B", "F'", "R", "F", "B'"),
    (Angle_elem_position.bdr3, Angle_elem_position.fdl1, Side_position.left) -> Array("D'", "R'", "D2", "R2", "D'"),

    (Angle_elem_position.ful1, Angle_elem_position.bdr1, Side_position.left) -> Array("F", "R'", "F'", "B", "R2", "B'"),
    (Angle_elem_position.ful2, Angle_elem_position.bdr1, Side_position.left) -> Array("F", "B", "R2", "B'", "F'"),
    (Angle_elem_position.ful3, Angle_elem_position.bdr1, Side_position.left) -> Array("F", "D'", "R2", "D", "F'"),
    (Angle_elem_position.fur1, Angle_elem_position.bdr1, Side_position.left) -> Array("B", "R2", "B'"),
    (Angle_elem_position.fur2, Angle_elem_position.bdr1, Side_position.left) -> Array("D'", "R2", "D"),
    (Angle_elem_position.fur3, Angle_elem_position.bdr1, Side_position.left) -> Array("R2", "B", "R'", "B'", "D'", "R2", "D"),
    (Angle_elem_position.fdl1, Angle_elem_position.bdr1, Side_position.left) -> Array("F'", "R", "F", "B", "R'", "B'"),
    (Angle_elem_position.fdl2, Angle_elem_position.bdr1, Side_position.left) -> Array("F'", "B", "R'", "B'", "F"),
    (Angle_elem_position.fdl3, Angle_elem_position.bdr1, Side_position.left) -> Array("D", "R", "D2", "D"),
    (Angle_elem_position.fdr1, Angle_elem_position.bdr1, Side_position.left) -> Array("B", "R'", "B'"),
    (Angle_elem_position.fdr2, Angle_elem_position.bdr1, Side_position.left) -> Array("R'", "D'", "R", "D", "B", "R2", "B'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bdr1, Side_position.left) -> Array("R", "D'", "R2", "D"),
    (Angle_elem_position.bul1, Angle_elem_position.bdr1, Side_position.left) -> Array("D'", "R", "D"),
    (Angle_elem_position.bul2, Angle_elem_position.bdr1, Side_position.left) -> Array("R", "B", "R'", "B'", "D'", "R2", "D"),
    (Angle_elem_position.bul3, Angle_elem_position.bdr1, Side_position.left) -> Array("R'", "B", "R2", "B'"),
    (Angle_elem_position.bur1, Angle_elem_position.bdr1, Side_position.left) -> Array("U", "D'", "R", "D", "U'"),
    (Angle_elem_position.bur2, Angle_elem_position.bdr1, Side_position.left) -> Array("U", "R'", "U'", "D'", "R", "D"),
    (Angle_elem_position.bur3, Angle_elem_position.bdr1, Side_position.left) -> Array("U", "R'", "U'", "R'", "B", "R2", "B'"),
    (Angle_elem_position.bdl1, Angle_elem_position.bdr1, Side_position.left) -> Array("B", "R'", "B'", "D'", "R2", "D"),
    (Angle_elem_position.bdl2, Angle_elem_position.bdr1, Side_position.left) -> Array("R'", "D'", "R", "D"),
    (Angle_elem_position.bdl3, Angle_elem_position.bdr1, Side_position.left) -> Array("R", "B", "R'", "B'"),
    (Angle_elem_position.bdr1, Angle_elem_position.bdr1, Side_position.left) -> Array(""),
    (Angle_elem_position.bdr2, Angle_elem_position.bdr1, Side_position.left) -> Array("D'", "R", "D", "R'", "D'", "R", "D"),
    (Angle_elem_position.bdr3, Angle_elem_position.bdr1, Side_position.left) -> Array("D'", "R2", "D", "B", "R2", "B'"),

    // start_side: front
    (Angle_elem_position.ful1, Angle_elem_position.ful1, Side_position.front) -> Array(""),
    (Angle_elem_position.ful2, Angle_elem_position.ful1, Side_position.front) -> Array("L'", "B", "L", "B'", "L'", "B", "L"),
    (Angle_elem_position.ful3, Angle_elem_position.ful1, Side_position.front) -> Array("L'", "B2", "L", "U", "B2", "U'"),
    (Angle_elem_position.fur1, Angle_elem_position.ful1, Side_position.front) -> Array("L'", "R", "B", "R'", "L"),
    (Angle_elem_position.fur2, Angle_elem_position.ful1, Side_position.front) -> Array("U'", "B'", "U2", "B2", "U'"),
    (Angle_elem_position.fur3, Angle_elem_position.ful1, Side_position.front) -> Array("R", "B'", "R'", "U", "B2", "U'"),
    (Angle_elem_position.fdl1, Angle_elem_position.ful1, Side_position.front) -> Array("D'", "B2", "D", "L'", "B'", "L"),
    (Angle_elem_position.fdl2, Angle_elem_position.ful1, Side_position.front) -> Array("U", "D'", "B'", "D", "U'"),
    (Angle_elem_position.fdl3, Angle_elem_position.ful1, Side_position.front) -> Array("L", "B2", "L2", "B", "L"),
    (Angle_elem_position.fdr1, Angle_elem_position.ful1, Side_position.front) -> Array("L'", "R'", "B2", "R", "L"),
    (Angle_elem_position.fdr2, Angle_elem_position.ful1, Side_position.front) -> Array("D", "L'", "B2", "L", "D'"),
    (Angle_elem_position.fdr3, Angle_elem_position.ful1, Side_position.front) -> Array("D", "U", "B2", "U'", "D'"),
    (Angle_elem_position.bul1, Angle_elem_position.ful1, Side_position.front) -> Array("B", "U", "B'", "U'", "L'", "B2", "L"),
    (Angle_elem_position.bul2, Angle_elem_position.ful1, Side_position.front) -> Array("B'", "U", "B2", "U'"),
    (Angle_elem_position.bul3, Angle_elem_position.ful1, Side_position.front) -> Array("L'", "B", "L"),
    (Angle_elem_position.bur1, Angle_elem_position.ful1, Side_position.front) -> Array("B2", "U", "B2", "U'"),
    (Angle_elem_position.bur2, Angle_elem_position.ful1, Side_position.front) -> Array("U", "B'", "U'", "L'", "B2", "L"),
    (Angle_elem_position.bur3, Angle_elem_position.ful1, Side_position.front) -> Array("B'", "L'", "B", "L"),
    (Angle_elem_position.bdl1, Angle_elem_position.ful1, Side_position.front) -> Array("B2", "U", "B'", "U'", "L'", "B2", "L"),
    (Angle_elem_position.bdl2, Angle_elem_position.ful1, Side_position.front) -> Array("L'", "B2", "L"),
    (Angle_elem_position.bdl3, Angle_elem_position.ful1, Side_position.front) -> Array("U", "B2", "U'"),
    (Angle_elem_position.bdr1, Angle_elem_position.ful1, Side_position.front) -> Array("U", "B'", "U'"),
    (Angle_elem_position.bdr2, Angle_elem_position.ful1, Side_position.front) -> Array("B", "L'", "B2", "L"),
    (Angle_elem_position.bdr3, Angle_elem_position.ful1, Side_position.front) -> Array("B'", "L'", "B", "L", "U", "B2", "U'"),

    (Angle_elem_position.ful1, Angle_elem_position.fur1, Side_position.front) -> Array("L'", "R", "B'", "R'", "L"),
    (Angle_elem_position.ful2, Angle_elem_position.fur1, Side_position.front) -> Array("L'", "B2", "U'", "B", "U"),
    (Angle_elem_position.ful3, Angle_elem_position.fur1, Side_position.front) -> Array("U", "B", "U2", "B2", "U"),
    (Angle_elem_position.fur1, Angle_elem_position.fur1, Side_position.front) -> Array(""),
    (Angle_elem_position.fur2, Angle_elem_position.fur1, Side_position.front) -> Array("R", "B2", "R'", "U'", "B2", "U"),
    (Angle_elem_position.fur3, Angle_elem_position.fur1, Side_position.front) -> Array("U'", "B2", "U", "R", "B2", "R'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fur1, Side_position.front) -> Array("D'", "R", "B2", "R'", "D"),
    (Angle_elem_position.fdl2, Angle_elem_position.fur1, Side_position.front) -> Array("L", "U'", "B2", "U", "L'"),
    (Angle_elem_position.fdl3, Angle_elem_position.fur1, Side_position.front) -> Array("D'", "U'", "B2", "U", "D"),
    (Angle_elem_position.fdr1, Angle_elem_position.fur1, Side_position.front) -> Array("D", "U'", "B", "U", "D'"),
    (Angle_elem_position.fdr2, Angle_elem_position.fur1, Side_position.front) -> Array("D", "B2", "D'", "R", "B'", "R'"),
    (Angle_elem_position.fdr3, Angle_elem_position.fur1, Side_position.front) -> Array("R'", "B'", "R2", "B2", "R'"),
    (Angle_elem_position.bul1, Angle_elem_position.fur1, Side_position.front) -> Array("B'", "U'", "B", "U"),
    (Angle_elem_position.bul2, Angle_elem_position.fur1, Side_position.front) -> Array("U'", "B", "U", "R", "B2", "R'"),
    (Angle_elem_position.bul3, Angle_elem_position.fur1, Side_position.front) -> Array("B", "R", "B'", "R'"),
    (Angle_elem_position.bur1, Angle_elem_position.fur1, Side_position.front) -> Array("B'", "U'", "B", "U", "R", "B2", "R'"),
    (Angle_elem_position.bur2, Angle_elem_position.fur1, Side_position.front) -> Array("B", "U'", "B2", "U"),
    (Angle_elem_position.bur3, Angle_elem_position.fur1, Side_position.front) -> Array("R", "B'", "R'"),
    (Angle_elem_position.bdl1, Angle_elem_position.fur1, Side_position.front) -> Array("U'", "B", "U"),
    (Angle_elem_position.bdl2, Angle_elem_position.fur1, Side_position.front) -> Array("B'", "R", "B2", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.fur1, Side_position.front) -> Array("B", "U'", "B", "U", "R", "B2", "R'"),
    (Angle_elem_position.bdr1, Angle_elem_position.fur1, Side_position.front) -> Array("B2", "U'", "B", "U", "R", "B2", "R'"),
    (Angle_elem_position.bdr2, Angle_elem_position.fur1, Side_position.front) -> Array("R", "B2", "R'"),
    (Angle_elem_position.bdr3, Angle_elem_position.fur1, Side_position.front) -> Array("U'", "B2", "U"),

    (Angle_elem_position.ful1, Angle_elem_position.fdl1, Side_position.front) -> Array("L'", "B'", "L", "D'", "B2", "D"),
    (Angle_elem_position.ful2, Angle_elem_position.fdl1, Side_position.front) -> Array("U", "D'", "B", "D", "U'"),
    (Angle_elem_position.ful3, Angle_elem_position.fdl1, Side_position.front) -> Array("U", "B'", "U'", "L", "B2", "L'"),
    (Angle_elem_position.fur1, Angle_elem_position.fdl1, Side_position.front) -> Array("R", "D'", "B2", "D", "R'"),
    (Angle_elem_position.fur2, Angle_elem_position.fdl1, Side_position.front) -> Array("U'", "L", "B2", "L'", "U"),
    (Angle_elem_position.fur3, Angle_elem_position.fdl1, Side_position.front) -> Array("R", "L", "B2", "L'", "R'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fdl1, Side_position.front) -> Array(""),
    (Angle_elem_position.fdl2, Angle_elem_position.fdl1, Side_position.front) -> Array("D'", "B2", "D", "L", "B2", "L'"),
    (Angle_elem_position.fdl3, Angle_elem_position.fdl1, Side_position.front) -> Array("L", "B2", "L'", "D'", "B2", "D"),
    (Angle_elem_position.fdr1, Angle_elem_position.fdl1, Side_position.front) -> Array("L", "R'", "B'", "R", "L'"),
    (Angle_elem_position.fdr2, Angle_elem_position.fdl1, Side_position.front) -> Array("D", "B2", "D2", "B2", "D"),
    (Angle_elem_position.fdr3, Angle_elem_position.fdl1, Side_position.front) -> Array("R'", "B2", "R", "D'", "B", "D"),
    (Angle_elem_position.bul1, Angle_elem_position.fdl1, Side_position.front) -> Array("B2", "L", "B'", "L'", "D'", "B2", "D"),
    (Angle_elem_position.bul2, Angle_elem_position.fdl1, Side_position.front) -> Array("L", "B2", "L'"),
    (Angle_elem_position.bul3, Angle_elem_position.fdl1, Side_position.front) -> Array("D'", "B2", "D"),
    (Angle_elem_position.bur1, Angle_elem_position.fdl1, Side_position.front) -> Array("B'", "L", "B2", "L'"),
    (Angle_elem_position.bur2, Angle_elem_position.fdl1, Side_position.front) -> Array("B", "L", "B'", "L'", "D'", "B2", "D"),
    (Angle_elem_position.bur3, Angle_elem_position.fdl1, Side_position.front) -> Array("D'", "B", "D"),
    (Angle_elem_position.bdl1, Angle_elem_position.fdl1, Side_position.front) -> Array("B'", "L", "B'", "L'", "D'", "B2", "D"),
    (Angle_elem_position.bdl2, Angle_elem_position.fdl1, Side_position.front) -> Array("B", "D'", "B2", "D"),
    (Angle_elem_position.bdl3, Angle_elem_position.fdl1, Side_position.front) -> Array("L", "B'", "L'"),
    (Angle_elem_position.bdr1, Angle_elem_position.fdl1, Side_position.front) -> Array("B", "L", "B'", "L'"),
    (Angle_elem_position.bdr2, Angle_elem_position.fdl1, Side_position.front) -> Array("B'", "D'", "B", "D"),
    (Angle_elem_position.bdr3, Angle_elem_position.fdl1, Side_position.front) -> Array("D'", "B", "D", "L", "B2", "L'"),

    (Angle_elem_position.ful1, Angle_elem_position.fdr1, Side_position.front) -> Array("R'", "U", "B2", "U'", "R"),
    (Angle_elem_position.ful2, Angle_elem_position.fdr1, Side_position.front) -> Array("L'", "D", "B2", "D'", "L"),
    (Angle_elem_position.ful3, Angle_elem_position.fdr1, Side_position.front) -> Array("L'", "R'", "B2", "R", "L"),
    (Angle_elem_position.fur1, Angle_elem_position.fdr1, Side_position.front) -> Array("U'", "D", "B'", "D'", "U"),
    (Angle_elem_position.fur2, Angle_elem_position.fdr1, Side_position.front) -> Array("R", "B", "R'", "D", "B2", "D'"),
    (Angle_elem_position.fur3, Angle_elem_position.fdr1, Side_position.front) -> Array("R", "B", "R2", "B2", "R"),
    (Angle_elem_position.fdl1, Angle_elem_position.fdr1, Side_position.front) -> Array("R'", "L", "B", "L'", "R"),
    (Angle_elem_position.fdl2, Angle_elem_position.fdr1, Side_position.front) -> Array("D'", "B'", "D", "R'", "B2", "R"),
    (Angle_elem_position.fdl3, Angle_elem_position.fdr1, Side_position.front) -> Array("D'", "B'", "D2", "D'"),
    (Angle_elem_position.fdr1, Angle_elem_position.fdr1, Side_position.front) -> Array(""),
    (Angle_elem_position.fdr2, Angle_elem_position.fdr1, Side_position.front) -> Array("R'", "B2", "R", "D", "B2", "D'"),
    (Angle_elem_position.fdr3, Angle_elem_position.fdr1, Side_position.front) -> Array("D", "B2", "D'", "R'", "B2", "R"),
    (Angle_elem_position.bul1, Angle_elem_position.fdr1, Side_position.front) -> Array("D", "B'", "D'"),
    (Angle_elem_position.bul2, Angle_elem_position.fdr1, Side_position.front) -> Array("B", "R'", "B2", "R"),
    (Angle_elem_position.bul3, Angle_elem_position.fdr1, Side_position.front) -> Array("B'", "R'", "B", "R", "D", "B2", "D'"),
    (Angle_elem_position.bur1, Angle_elem_position.fdr1, Side_position.front) -> Array("R'", "B2", "R"),
    (Angle_elem_position.bur2, Angle_elem_position.fdr1, Side_position.front) -> Array("D", "B2", "D'"),
    (Angle_elem_position.bur3, Angle_elem_position.fdr1, Side_position.front) -> Array("B2", "R'", "B", "R", "D", "B2", "D'"),
    (Angle_elem_position.bdl1, Angle_elem_position.fdr1, Side_position.front) -> Array("B", "D", "B'", "D'"),
    (Angle_elem_position.bdl2, Angle_elem_position.fdr1, Side_position.front) -> Array("R'", "B", "R", "D", "B2", "D'"),
    (Angle_elem_position.bdl3, Angle_elem_position.fdr1, Side_position.front) -> Array("B'", "R'", "B", "R"),
    (Angle_elem_position.bdr1, Angle_elem_position.fdr1, Side_position.front) -> Array("R'", "B", "R"),
    (Angle_elem_position.bdr2, Angle_elem_position.fdr1, Side_position.front) -> Array("B", "R'", "B", "R", "D", "B2", "D'"),
    (Angle_elem_position.bdr3, Angle_elem_position.fdr1, Side_position.front) -> Array("B'", "D", "B2", "D'"),

    // start_side: right
    (Angle_elem_position.ful1, Angle_elem_position.fur1, Side_position.right) -> Array("L", "U", "L'", "U'"),
    (Angle_elem_position.ful2, Angle_elem_position.fur1, Side_position.right) -> Array("L'", "F'", "L", "F"),
    (Angle_elem_position.ful3, Angle_elem_position.fur1, Side_position.right) -> Array("U", "L'", "U'", "F'", "L2", "F"),
    (Angle_elem_position.fur1, Angle_elem_position.fur1, Side_position.right) -> Array(""),
    (Angle_elem_position.fur2, Angle_elem_position.fur1, Side_position.right) -> Array("U", "L2", "U'", "F'", "L2", "F"),
    (Angle_elem_position.fur3, Angle_elem_position.fur1, Side_position.right) -> Array("F'", "L2", "F", "U", "L2", "U'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fur1, Side_position.right) -> Array("L", "F'", "L2", "F"),
    (Angle_elem_position.fdl2, Angle_elem_position.fur1, Side_position.right) -> Array("U", "L'", "U'"),
    (Angle_elem_position.fdl3, Angle_elem_position.fur1, Side_position.right) -> Array("L'", "U", "L'", "U'", "F'", "L2", "F"),
    (Angle_elem_position.fdr1, Angle_elem_position.fur1, Side_position.right) -> Array("D'", "L", "D", "F'", "F2", "F"),
    (Angle_elem_position.fdr2, Angle_elem_position.fur1, Side_position.right) -> Array("D'", "U", "L'", "U'", "D"),
    (Angle_elem_position.fdr3, Angle_elem_position.fur1, Side_position.right) -> Array("F", "L", "F2", "L2", "F"),
    (Angle_elem_position.bul1, Angle_elem_position.fur1, Side_position.right) -> Array("B", "F'", "L", "F", "B'"),
    (Angle_elem_position.bul2, Angle_elem_position.fur1, Side_position.right) -> Array("U'", "L'", "U2", "L2", "U'"),
    (Angle_elem_position.bul3, Angle_elem_position.fur1, Side_position.right) -> Array("U'", "F'", "L", "F", "U"),
    (Angle_elem_position.bur1, Angle_elem_position.fur1, Side_position.right) -> Array("F'", "B", "L2", "B'", "F"),
    (Angle_elem_position.bur2, Angle_elem_position.fur1, Side_position.right) -> Array("F'", "L", "F"),
    (Angle_elem_position.bur3, Angle_elem_position.fur1, Side_position.right) -> Array("L'", "U", "L2", "U'"),
    (Angle_elem_position.bdl1, Angle_elem_position.fur1, Side_position.right) -> Array("B'", "U", "L2", "U'", "B"),
    (Angle_elem_position.bdl2, Angle_elem_position.fur1, Side_position.right) -> Array("D", "F'", "L2", "F", "D'"),
    (Angle_elem_position.bdl3, Angle_elem_position.fur1, Side_position.right) -> Array("D", "U", "L2", "U'", "D'"),
    (Angle_elem_position.bdr1, Angle_elem_position.fur1, Side_position.right) -> Array("F", "L2", "F'"),
    (Angle_elem_position.bdr2, Angle_elem_position.fur1, Side_position.right) -> Array("L2", "U", "L'", "U'", "F'", "L2", "F"),
    (Angle_elem_position.bdr3, Angle_elem_position.fur1, Side_position.right) -> Array("U", "L2", "U'"),

    (Angle_elem_position.ful1, Angle_elem_position.bul1, Side_position.right) -> Array("L'", "U'", "L", "U", "B", "L2", "B'"),
    (Angle_elem_position.ful2, Angle_elem_position.bul1, Side_position.right) -> Array("B", "L'", "B'"),
    (Angle_elem_position.ful3, Angle_elem_position.bul1, Side_position.right) -> Array("L", "U'", "L2", "U"),
    (Angle_elem_position.fur1, Angle_elem_position.bul1, Side_position.right) -> Array("F'", "B", "L'", "B'", "F"),
    (Angle_elem_position.fur2, Angle_elem_position.bul1, Side_position.right) -> Array("F'", "L2", "F", "U'", "L", "U"),
    (Angle_elem_position.fur3, Angle_elem_position.bul1, Side_position.right) -> Array("U", "L2", "U2", "L", "U"),
    (Angle_elem_position.fdl1, Angle_elem_position.bul1, Side_position.right) -> Array("B", "L2", "B'"),
    (Angle_elem_position.fdl2, Angle_elem_position.bul1, Side_position.right) -> Array("L2", "U'", "L", "U", "B", "L2", "B'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bul1, Side_position.right) -> Array("U'", "L2", "U"),
    (Angle_elem_position.fdr1, Angle_elem_position.bul1, Side_position.right) -> Array("D'", "B", "L2", "B'", "D"),
    (Angle_elem_position.fdr2, Angle_elem_position.bul1, Side_position.right) -> Array("F", "U'", "L2", "U", "F'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bul1, Side_position.right) -> Array("D'", "U'", "L2", "U", "D"),
    (Angle_elem_position.bul1, Angle_elem_position.bul1, Side_position.right) -> Array(""),
    (Angle_elem_position.bul2, Angle_elem_position.bul1, Side_position.right) -> Array("B", "L2", "B'", "U'", "L2", "U"),
    (Angle_elem_position.bul3, Angle_elem_position.bul1, Side_position.right) -> Array("U'", "L2", "U", "B", "L2", "B'"),
    (Angle_elem_position.bur1, Angle_elem_position.bul1, Side_position.right) -> Array("L'", "U'", "L", "U"),
    (Angle_elem_position.bur2, Angle_elem_position.bul1, Side_position.right) -> Array("L", "B", "L'", "B'"),
    (Angle_elem_position.bur3, Angle_elem_position.bul1, Side_position.right) -> Array("U'", "L", "U", "B", "L2", "B'"),
    (Angle_elem_position.bdl1, Angle_elem_position.bul1, Side_position.right) -> Array("U'", "D", "L", "D'", "U"),
    (Angle_elem_position.bdl2, Angle_elem_position.bul1, Side_position.right) -> Array("D", "L2", "D'", "B", "L'", "B'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bul1, Side_position.right) -> Array("B'", "L2", "B2", "L'", "B'"),
    (Angle_elem_position.bdr1, Angle_elem_position.bul1, Side_position.right) -> Array("L'", "B", "L2", "B'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bul1, Side_position.right) -> Array("U'", "L", "U"),
    (Angle_elem_position.bdr3, Angle_elem_position.bul1, Side_position.right) -> Array("L", "U'", "L", "U", "B", "L2", "B'"),

    (Angle_elem_position.ful1, Angle_elem_position.fdr1, Side_position.right) -> Array("L'", "F", "L2", "F'"),
    (Angle_elem_position.ful2, Angle_elem_position.fdr1, Side_position.right) -> Array("D'", "L", "D"),
    (Angle_elem_position.ful3, Angle_elem_position.fdr1, Side_position.right) -> Array("L", "F", "L'", "F'", "D'", "L2", "D"),
    (Angle_elem_position.fur1, Angle_elem_position.fdr1, Side_position.right) -> Array("F'", "L'", "F", "D'", "L2", "D"),
    (Angle_elem_position.fur2, Angle_elem_position.fdr1, Side_position.right) -> Array("U", "D'", "L", "D", "U'"),
    (Angle_elem_position.fur3, Angle_elem_position.fdr1, Side_position.right) -> Array("F'", "L'", "F2", "L2", "F'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fdr1, Side_position.right) -> Array("F", "L", "F'"),
    (Angle_elem_position.fdl2, Angle_elem_position.fdr1, Side_position.right) -> Array("L", "F", "L'", "F'"),
    (Angle_elem_position.fdl3, Angle_elem_position.fdr1, Side_position.right) -> Array("F", "L'", "F'", "D'", "L2", "D"),
    (Angle_elem_position.fdr1, Angle_elem_position.fdr1, Side_position.right) -> Array(""),
    (Angle_elem_position.fdr2, Angle_elem_position.fdr1, Side_position.right) -> Array("D'", "L2", "D", "F", "L2", "F'"),
    (Angle_elem_position.fdr3, Angle_elem_position.fdr1, Side_position.right) -> Array("F", "L2", "F'", "D'", "L2", "D"),
    (Angle_elem_position.bul1, Angle_elem_position.fdr1, Side_position.right) -> Array("B", "D", "L2", "D'", "B'"),
    (Angle_elem_position.bul2, Angle_elem_position.fdr1, Side_position.right) -> Array("U'", "F", "L2", "F'", "U"),
    (Angle_elem_position.bul3, Angle_elem_position.fdr1, Side_position.right) -> Array("U'", "D'", "L2", "D", "U"),
    (Angle_elem_position.bur1, Angle_elem_position.fdr1, Side_position.right) -> Array("L2", "F", "L'", "F'", "D'", "L2", "D"),
    (Angle_elem_position.bur2, Angle_elem_position.fdr1, Side_position.right) -> Array("D'", "L2", "D"),
    (Angle_elem_position.bur3, Angle_elem_position.fdr1, Side_position.right) -> Array("F", "L2", "F'"),
    (Angle_elem_position.bdl1, Angle_elem_position.fdr1, Side_position.right) -> Array("F", "B'", "L'", "B", "F'"),
    (Angle_elem_position.bdl2, Angle_elem_position.fdr1, Side_position.right) -> Array("D", "L", "D2", "L2", "D"),
    (Angle_elem_position.bdl3, Angle_elem_position.fdr1, Side_position.right) -> Array("D", "L", "D'", "F", "L2", "F'"),
    (Angle_elem_position.bdr1, Angle_elem_position.fdr1, Side_position.right) -> Array("L", "D'", "L2", "D"),
    (Angle_elem_position.bdr2, Angle_elem_position.fdr1, Side_position.right) -> Array("L'", "F", "L2", "F'", "D'", "L2", "D"),
    (Angle_elem_position.bdr3, Angle_elem_position.fdr1, Side_position.right) -> Array("F", "L'", "F'"),

    (Angle_elem_position.ful1, Angle_elem_position.bdl1, Side_position.right) -> Array("B'", "L2", "B"),
    (Angle_elem_position.ful2, Angle_elem_position.bdl1, Side_position.right) -> Array("L2", "D", "L'", "D'", "B'", "L2", "B"),
    (Angle_elem_position.ful3, Angle_elem_position.bdl1, Side_position.right) -> Array("D", "L2", "D'"),
    (Angle_elem_position.fur1, Angle_elem_position.bdl1, Side_position.right) -> Array("B'", "U", "L2", "U'", "B"),
    (Angle_elem_position.fur2, Angle_elem_position.bdl1, Side_position.right) -> Array("F'", "D", "L2", "D'", "F"),
    (Angle_elem_position.fur3, Angle_elem_position.bdl1, Side_position.right) -> Array("F'", "B'", "L2", "B", "F"),
    (Angle_elem_position.fdl1, Angle_elem_position.bdl1, Side_position.right) -> Array("L", "B'", "L", "B", "D", "L2", "D'"),
    (Angle_elem_position.fdl2, Angle_elem_position.bdl1, Side_position.right) -> Array("B", "L", "B'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bdl1, Side_position.right) -> Array("L'", "D", "L2", "D'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bdl1, Side_position.right) -> Array("F", "B'", "L", "B", "F'"),
    (Angle_elem_position.fdr2, Angle_elem_position.bdl1, Side_position.right) -> Array("D'", "L'", "D2", "L2", "D'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bdl1, Side_position.right) -> Array("D'", "L'", "D", "B'", "L2", "B"),
    (Angle_elem_position.bul1, Angle_elem_position.bdl1, Side_position.right) -> Array("U'", "D", "L'", "D'", "U"),
    (Angle_elem_position.bul2, Angle_elem_position.bdl1, Side_position.right) -> Array("B", "L", "B'", "D", "L2", "D'"),
    (Angle_elem_position.bul3, Angle_elem_position.bdl1, Side_position.right) -> Array("B", "L", "B2", "L2", "B"),
    (Angle_elem_position.bur1, Angle_elem_position.bdl1, Side_position.right) -> Array("D", "L'", "D'"),
    (Angle_elem_position.bur2, Angle_elem_position.bdl1, Side_position.right) -> Array("B", "L'", "B2", "L", "B"),
    (Angle_elem_position.bur3, Angle_elem_position.bdl1, Side_position.right) -> Array("L", "D", "L2", "D'"),
    (Angle_elem_position.bdl1, Angle_elem_position.bdl1, Side_position.right) -> Array(""),
    (Angle_elem_position.bdl2, Angle_elem_position.bdl1, Side_position.right) -> Array("B'", "L2", "B", "D", "L2", "D'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bdl1, Side_position.right) -> Array("D", "L2", "D'", "B'", "L2", "B"),
    (Angle_elem_position.bdr1, Angle_elem_position.bdl1, Side_position.right) -> Array("B'", "L", "B", "D", "L2", "D'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bdl1, Side_position.right) -> Array("L", "D", "L'", "D'"),
    (Angle_elem_position.bdr3, Angle_elem_position.bdl1, Side_position.right) -> Array("L'", "B'", "L", "B"),

    // start_side: back
    (Angle_elem_position.ful1, Angle_elem_position.bul1, Side_position.back) -> Array("F", "U", "F'", "U'", "R'", "F2", "R"),
    (Angle_elem_position.ful2, Angle_elem_position.bul1, Side_position.back) -> Array("F'", "U", "F2", "U'"),
    (Angle_elem_position.ful3, Angle_elem_position.bul1, Side_position.back) -> Array("R'", "F", "R"),
    (Angle_elem_position.fur1, Angle_elem_position.bul1, Side_position.back) -> Array("R'", "F'", "R"),
    (Angle_elem_position.fur2, Angle_elem_position.bul1, Side_position.back) -> Array("U", "F", "U'"),
    (Angle_elem_position.fur3, Angle_elem_position.bul1, Side_position.back) -> Array("U", "F'", "U'", "R'", "F2", "R"),
    (Angle_elem_position.fdl1, Angle_elem_position.bul1, Side_position.back) -> Array("F2", "U", "F'", "U'", "R'", "F2", "R"),
    (Angle_elem_position.fdl2, Angle_elem_position.bul1, Side_position.back) -> Array("R'", "F2", "R"),
    (Angle_elem_position.fdl3, Angle_elem_position.bul1, Side_position.back) -> Array("U", "F2", "U'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bul1, Side_position.back) -> Array("F", "R'", "F2", "R"),
    (Angle_elem_position.fdr2, Angle_elem_position.bul1, Side_position.back) -> Array("U", "F'", "U'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bul1, Side_position.back) -> Array("D'", "U", "F2", "U'", "D"),
    (Angle_elem_position.bul1, Angle_elem_position.bul1, Side_position.back) -> Array(""),
    (Angle_elem_position.bul2, Angle_elem_position.bul1, Side_position.back) -> Array("U", "F2", "U'", "R'", "F2", "R"),
    (Angle_elem_position.bul3, Angle_elem_position.bul1, Side_position.back) -> Array("R'", "F2", "R", "U", "F2", "U'"),
    (Angle_elem_position.bur1, Angle_elem_position.bul1, Side_position.back) -> Array("R'", "L", "F", "L'", "R"),
    (Angle_elem_position.bur2, Angle_elem_position.bul1, Side_position.back) -> Array("L", "F2", "L'", "U", "F'", "U'"),
    (Angle_elem_position.bur3, Angle_elem_position.bul1, Side_position.back) -> Array("U'", "F'", "U2", "F2", "U'"),
    (Angle_elem_position.bdl1, Angle_elem_position.bul1, Side_position.back) -> Array("D'", "F2", "D", "R'", "F", "R"),
    (Angle_elem_position.bdl2, Angle_elem_position.bul1, Side_position.back) -> Array("D'", "U", "F'", "U'", "D"),
    (Angle_elem_position.bdl3, Angle_elem_position.bul1, Side_position.back) -> Array("R", "F2", "R2", "F", "R"),
    (Angle_elem_position.bdr1, Angle_elem_position.bul1, Side_position.back) -> Array("D", "R'", "F2", "R", "D'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bul1, Side_position.back) -> Array("L'", "U", "F2", "U'", "L"),
    (Angle_elem_position.bdr3, Angle_elem_position.bul1, Side_position.back) -> Array("D", "U", "F2", "U'", "D'"),

    (Angle_elem_position.ful1, Angle_elem_position.bur1, Side_position.back) -> Array("F'", "U'", "F", "U"),
    (Angle_elem_position.ful2, Angle_elem_position.bur1, Side_position.back) -> Array("U'", "F", "U", "L", "F2", "L'"),
    (Angle_elem_position.ful3, Angle_elem_position.bur1, Side_position.back) -> Array("F", "L", "F'", "L'"),
    (Angle_elem_position.fur1, Angle_elem_position.bur1, Side_position.back) -> Array("F'", "U'", "F", "U", "L", "F2", "L'"),
    (Angle_elem_position.fur2, Angle_elem_position.bur1, Side_position.back) -> Array("L", "F'", "L'"),
    (Angle_elem_position.fur3, Angle_elem_position.bur1, Side_position.back) -> Array("F", "U'", "F'", "U"),
    (Angle_elem_position.fdl1, Angle_elem_position.bur1, Side_position.back) -> Array("U'", "F", "U"),
    (Angle_elem_position.fdl2, Angle_elem_position.bur1, Side_position.back) -> Array("F'", "L", "F2", "L'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bur1, Side_position.back) -> Array("F", "U'", "F", "U", "L", "F2", "L'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bur1, Side_position.back) -> Array("L", "F2", "L'"),
    (Angle_elem_position.fdr2, Angle_elem_position.bur1, Side_position.back) -> Array("F2", "U'", "F", "U", "L", "F2", "L'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bur1, Side_position.back) -> Array("U'", "F2", "U"),
    (Angle_elem_position.bul1, Angle_elem_position.bur1, Side_position.back) -> Array("R'", "L", "F'", "L'", "R"),
    (Angle_elem_position.bul2, Angle_elem_position.bur1, Side_position.back) -> Array("U", "F", "U2", "F2", "U"),
    (Angle_elem_position.bul3, Angle_elem_position.bur1, Side_position.back) -> Array("R'", "F", "R", "U'", "F2", "U"),
    (Angle_elem_position.bur1, Angle_elem_position.bur1, Side_position.back) -> Array(""),
    (Angle_elem_position.bur2, Angle_elem_position.bur1, Side_position.back) -> Array("U", "F2", "U'", "L", "L2", "L'"),
    (Angle_elem_position.bur3, Angle_elem_position.bur1, Side_position.back) -> Array("L", "F2", "L'", "U'", "L2", "U"),
    (Angle_elem_position.bdl1, Angle_elem_position.bur1, Side_position.back) -> Array("D'", "L", "F2", "L'", "D"),
    (Angle_elem_position.bdl2, Angle_elem_position.bur1, Side_position.back) -> Array("R", "L", "F2", "L'", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bur1, Side_position.back) -> Array("R", "L", "F2", "L'", "R'"),
    (Angle_elem_position.bdr1, Angle_elem_position.bur1, Side_position.back) -> Array("D", "F2", "D'", "L", "F'", "L'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bur1, Side_position.back) -> Array("U'", "D", "F", "D'", "U"),
    (Angle_elem_position.bdr3, Angle_elem_position.bur1, Side_position.back) -> Array("L'", "F'", "L2", "F2", "L'"),

    (Angle_elem_position.ful1, Angle_elem_position.bdl1, Side_position.back) -> Array("F2", "R", "F'", "R'", "D'", "F2", "D"),
    (Angle_elem_position.ful2, Angle_elem_position.bdl1, Side_position.back) -> Array("R", "F2", "R'"),
    (Angle_elem_position.ful3, Angle_elem_position.bdl1, Side_position.back) -> Array("D'", "F2", "D"),
    (Angle_elem_position.fur1, Angle_elem_position.bdl1, Side_position.back) -> Array("F'", "R", "F2", "R'"),
    (Angle_elem_position.fur2, Angle_elem_position.bdl1, Side_position.back) -> Array("F", "R", "F'", "R'", "D'", "F2", "D"),
    (Angle_elem_position.fur3, Angle_elem_position.bdl1, Side_position.back) -> Array("D'", "F", "D"),
    (Angle_elem_position.fdl1, Angle_elem_position.bdl1, Side_position.back) -> Array("F'", "R", "F'", "R'", "D'", "F2", "D"),
    (Angle_elem_position.fdl2, Angle_elem_position.bdl1, Side_position.back) -> Array("F'", "D'", "F2", "D"),
    (Angle_elem_position.fdl3, Angle_elem_position.bdl1, Side_position.back) -> Array("R", "F'", "R'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bdl1, Side_position.back) -> Array("F'", "D'", "F", "D"),
    (Angle_elem_position.fdr2, Angle_elem_position.bdl1, Side_position.back) -> Array("F2", "R", "F2", "R'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bdl1, Side_position.back) -> Array("R", "F'", "R'", "D'", "F2", "D"),
    (Angle_elem_position.bul1, Angle_elem_position.bdl1, Side_position.back) -> Array("R'", "F'", "R", "D'", "F2", "D"),
    (Angle_elem_position.bul2, Angle_elem_position.bdl1, Side_position.back) -> Array("U", "D'", "F", "D", "U'"),
    (Angle_elem_position.bul3, Angle_elem_position.bdl1, Side_position.back) -> Array("R'", "F'", "R2", "F2", "R'"),
    (Angle_elem_position.bur1, Angle_elem_position.bdl1, Side_position.back) -> Array("L", "D'", "F2", "D", "L'"),
    (Angle_elem_position.bur2, Angle_elem_position.bdl1, Side_position.back) -> Array("L", "R", "F2", "R'", "L'"),
    (Angle_elem_position.bur3, Angle_elem_position.bdl1, Side_position.back) -> Array("U", "R", "F2", "R'", "U'"),
    (Angle_elem_position.bdl1, Angle_elem_position.bdl1, Side_position.back) -> Array(""),
    (Angle_elem_position.bdl2, Angle_elem_position.bdl1, Side_position.back) -> Array("D'", "F2", "D", "R", "F2", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bdl1, Side_position.back) -> Array("R", "F2", "R'", "D'", "F2", "D"),
    (Angle_elem_position.bdr1, Angle_elem_position.bdl1, Side_position.back) -> Array("D", "F", "D2", "F2", "D"),
    (Angle_elem_position.bdr2, Angle_elem_position.bdl1, Side_position.back) -> Array("L'", "R", "F'", "R'", "L"),
    (Angle_elem_position.bdr3, Angle_elem_position.bdl1, Side_position.back) -> Array("D", "F", "D'", "R", "F2", "R'"),

    (Angle_elem_position.ful1, Angle_elem_position.bdr1, Side_position.back) -> Array("F", "L'", "F2", "L"),
    (Angle_elem_position.ful2, Angle_elem_position.bdr1, Side_position.back) -> Array("F'", "L'", "F", "L", "D", "F2", "D'"),
    (Angle_elem_position.ful3, Angle_elem_position.bdr1, Side_position.back) -> Array("D", "F'", "D'"),
    (Angle_elem_position.fur1, Angle_elem_position.bdr1, Side_position.back) -> Array("F2", "L'", "F", "L", "D", "F2", "D'"),
    (Angle_elem_position.fur2, Angle_elem_position.bdr1, Side_position.back) -> Array("D", "F2", "D'"),
    (Angle_elem_position.fur3, Angle_elem_position.bdr1, Side_position.back) -> Array("L'", "F2", "L"),
    (Angle_elem_position.fdl1, Angle_elem_position.bdr1, Side_position.back) -> Array("F'", "L'", "F", "L"),
    (Angle_elem_position.fdl2, Angle_elem_position.bdr1, Side_position.back) -> Array("F", "D", "F'", "D'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bdr1, Side_position.back) -> Array("L'", "F", "L", "D", "F2", "D'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bdr1, Side_position.back) -> Array("F'", "D", "F2", "D'"),
    (Angle_elem_position.fdr2, Angle_elem_position.bdr1, Side_position.back) -> Array("F", "L'", "F", "L", "D", "F2", "D'"),
    (Angle_elem_position.fdr3, Angle_elem_position.bdr1, Side_position.back) -> Array("L'", "F", "L"),
    (Angle_elem_position.bul1, Angle_elem_position.bdr1, Side_position.back) -> Array("R'", "D", "F2", "D'", "R"),
    (Angle_elem_position.bul2, Angle_elem_position.bdr1, Side_position.back) -> Array("R'", "L'", "F2", "L", "R"),
    (Angle_elem_position.bul3, Angle_elem_position.bdr1, Side_position.back) -> Array("U", "D", "F2", "D'", "U'"),
    (Angle_elem_position.bur1, Angle_elem_position.bdr1, Side_position.back) -> Array("L'", "F", "L", "D", "F2", "D'"),
    (Angle_elem_position.bur2, Angle_elem_position.bdr1, Side_position.back) -> Array("U'", "D", "F'", "D'", "U"),
    (Angle_elem_position.bur3, Angle_elem_position.bdr1, Side_position.back) -> Array("L'", "F", "L2", "F2", "L"),
    (Angle_elem_position.bdl1, Angle_elem_position.bdr1, Side_position.back) -> Array("D'", "F'", "D2", "F2", "D'"),
    (Angle_elem_position.bdl2, Angle_elem_position.bdr1, Side_position.back) -> Array("R", "L'", "F", "L", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bdr1, Side_position.back) -> Array("D'", "F'", "D", "L'", "F2", "L"),
    (Angle_elem_position.bdr1, Angle_elem_position.bdr1, Side_position.back) -> Array(""),
    (Angle_elem_position.bdr2, Angle_elem_position.bdr1, Side_position.back) -> Array("D", "F2", "D'", "L'", "F2", "L"),
    (Angle_elem_position.bdr3, Angle_elem_position.bdr1, Side_position.back) -> Array("L'", "F2", "L", "D", "F2", "D'"),

    // start_side: down
    (Angle_elem_position.ful1, Angle_elem_position.fdl1, Side_position.down) -> Array("U", "F", "U'", "F'"),
    (Angle_elem_position.ful2, Angle_elem_position.fdl1, Side_position.down) -> Array("U'", "L'", "U", "L"),
    (Angle_elem_position.ful3, Angle_elem_position.fdl1, Side_position.down) -> Array("L'", "U", "L", "F", "U2", "F'"),
    (Angle_elem_position.fur1, Angle_elem_position.fdl1, Side_position.down) -> Array("U'", "F", "U2", "F'"),
    (Angle_elem_position.fur2, Angle_elem_position.fdl1, Side_position.down) -> Array("L'", "U", "L"),
    (Angle_elem_position.fur3, Angle_elem_position.fdl1, Side_position.down) -> Array("U", "L'", "U", "L", "F", "U2", "F'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fdl1, Side_position.down) -> Array(""),
    (Angle_elem_position.fdl2, Angle_elem_position.fdl1, Side_position.down) -> Array("L'", "U2", "L", "F", "U2", "F'"),
    (Angle_elem_position.fdl3, Angle_elem_position.fdl1, Side_position.down) -> Array("F", "U2", "F'", "L'", "U2", "L"),
    (Angle_elem_position.fdr1, Angle_elem_position.fdl1, Side_position.down) -> Array("R", "U2", "R'", "F", "U'", "F'"),
    (Angle_elem_position.fdr2, Angle_elem_position.fdl1, Side_position.down) -> Array("F'", "U'", "F2", "U2", "F'"),
    (Angle_elem_position.fdr3, Angle_elem_position.fdl1, Side_position.down) -> Array("R", "L'", "U", "L", "R'"),
    (Angle_elem_position.bul1, Angle_elem_position.fdl1, Side_position.down) -> Array("B", "F", "U2", "F'", "B'"),
    (Angle_elem_position.bul2, Angle_elem_position.fdl1, Side_position.down) -> Array("R'", "F", "U2", "F'", "R"),
    (Angle_elem_position.bul3, Angle_elem_position.fdl1, Side_position.down) -> Array("B", "L'", "U2", "L", "B'"),
    (Angle_elem_position.bur1, Angle_elem_position.fdl1, Side_position.down) -> Array("B'", "F", "U'", "F'", "B"),
    (Angle_elem_position.bur2, Angle_elem_position.fdl1, Side_position.down) -> Array("L", "U", "L'", "F", "U2", "F'"),
    (Angle_elem_position.bur3, Angle_elem_position.fdl1, Side_position.down) -> Array("L", "U", "L2", "U2", "L"),
    (Angle_elem_position.bdl1, Angle_elem_position.fdl1, Side_position.down) -> Array("B", "F", "U2", "F'", "B'"),
    (Angle_elem_position.bdl2, Angle_elem_position.fdl1, Side_position.down) -> Array("R", "F", "U2", "F'", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.fdl1, Side_position.down) -> Array("B", "L'", "U2", "L", "B'"),
    (Angle_elem_position.bdr1, Angle_elem_position.fdl1, Side_position.down) -> Array("B'", "F", "U'", "F'", "B"),
    (Angle_elem_position.bdr2, Angle_elem_position.fdl1, Side_position.down) -> Array("L", "U", "L'", "F", "U2", "F'"),
    (Angle_elem_position.bdr3, Angle_elem_position.fdl1, Side_position.down) -> Array("L", "U", "L2", "U2", "L"),

    (Angle_elem_position.ful1, Angle_elem_position.fdr1, Side_position.down) -> Array("R", "U'", "R'"),
    (Angle_elem_position.ful2, Angle_elem_position.fdr1, Side_position.down) -> Array("U", "F'", "U2", "F"),
    (Angle_elem_position.ful3, Angle_elem_position.fdr1, Side_position.down) -> Array("U'", "F'", "U", "F", "R", "U2", "R'"),
    (Angle_elem_position.fur1, Angle_elem_position.fdr1, Side_position.down) -> Array("U", "R", "U'", "R'"),
    (Angle_elem_position.fur2, Angle_elem_position.fdr1, Side_position.down) -> Array("U'", "F'", "U", "F"),
    (Angle_elem_position.fur3, Angle_elem_position.fdr1, Side_position.down) -> Array("F'", "U", "F", "R", "U2", "R'"),
    (Angle_elem_position.fdl1, Angle_elem_position.fdr1, Side_position.down) -> Array("L'", "U2", "L", "F'", "U", "F"),
    (Angle_elem_position.fdl2, Angle_elem_position.fdr1, Side_position.down) -> Array("L'", "R", "U'", "R'", "L"),
    (Angle_elem_position.fdl3, Angle_elem_position.fdr1, Side_position.down) -> Array("F", "U2", "F2", "U", "F"),
    (Angle_elem_position.fdr1, Angle_elem_position.fdr1, Side_position.down) -> Array(""),
    (Angle_elem_position.fdr2, Angle_elem_position.fdr1, Side_position.down) -> Array("F'", "U2", "F", "R", "U2", "R'"),
    (Angle_elem_position.fdr3, Angle_elem_position.fdr1, Side_position.down) -> Array("R", "U2", "R'", "F'", "U2", "F"),
    (Angle_elem_position.bul1, Angle_elem_position.fdr1, Side_position.down) -> Array("U'", "R", "U2", "R'"),
    (Angle_elem_position.bul2, Angle_elem_position.fdr1, Side_position.down) -> Array("F'", "U", "F"),
    (Angle_elem_position.bul3, Angle_elem_position.fdr1, Side_position.down) -> Array("U", "F'", "U", "F", "R", "U2", "R'"),
    (Angle_elem_position.bur1, Angle_elem_position.fdr1, Side_position.down) -> Array("R", "U2", "R'"),
    (Angle_elem_position.bur2, Angle_elem_position.fdr1, Side_position.down) -> Array("U2", "F'", "U", "F", "R", "U2", "R'"),
    (Angle_elem_position.bur3, Angle_elem_position.fdr1, Side_position.down) -> Array("F'", "U2", "F"),
    (Angle_elem_position.bdl1, Angle_elem_position.fdr1, Side_position.down) -> Array("B", "U2", "B'", "R", "U'", "R'"),
    (Angle_elem_position.bdl2, Angle_elem_position.fdr1, Side_position.down) -> Array("R'", "U'", "R2", "U2", "R'"),
    (Angle_elem_position.bdl3, Angle_elem_position.fdr1, Side_position.down) -> Array("F'", "B", "U", "B'", "F"),
    (Angle_elem_position.bdr1, Angle_elem_position.fdr1, Side_position.down) -> Array("B'", "R", "U2", "R'", "B"),
    (Angle_elem_position.bdr2, Angle_elem_position.fdr1, Side_position.down) -> Array("L", "R", "U2", "R'", "L'"),
    (Angle_elem_position.bdr3, Angle_elem_position.fdr1, Side_position.down) -> Array("L", "F'", "U2", "F", "L'"),

    (Angle_elem_position.ful1, Angle_elem_position.bdr1, Side_position.down) -> Array("B'", "U", "B"),
    (Angle_elem_position.ful2, Angle_elem_position.bdr1, Side_position.down) -> Array("U", "L", "U'", "L'", "B'", "U2", "B"),
    (Angle_elem_position.ful3, Angle_elem_position.bdr1, Side_position.down) -> Array("U'", "L", "U2", "L'"),
    (Angle_elem_position.fur1, Angle_elem_position.bdr1, Side_position.down) -> Array("B'", "U2", "B"),
    (Angle_elem_position.fur2, Angle_elem_position.bdr1, Side_position.down) -> Array("U2", "L", "U'", "L'", "B'", "U2", "B"),
    (Angle_elem_position.fur3, Angle_elem_position.bdr1, Side_position.down) -> Array("L", "U2", "L'"),
    (Angle_elem_position.fdl1, Angle_elem_position.bdr1, Side_position.down) -> Array("F", "B'", "U", "B", "F'"),
    (Angle_elem_position.fdl2, Angle_elem_position.bdr1, Side_position.down) -> Array("F", "U2", "F'", "L", "U'", "L'"),
    (Angle_elem_position.fdl3, Angle_elem_position.bdr1, Side_position.down) -> Array("L'", "U'", "L2", "U2", "L'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bdr1, Side_position.down) -> Array("R", "B'", "U2", "B", "R'"),
    (Angle_elem_position.fdr2, Angle_elem_position.bdr1, Side_position.down) -> Array("F'", "B'", "U2", "B", "F"),
    (Angle_elem_position.fdr3, Angle_elem_position.bdr1, Side_position.down) -> Array("F'", "L", "U2", "L'", "F"),
    (Angle_elem_position.bul1, Angle_elem_position.bdr1, Side_position.down) -> Array("U", "B'", "U2", "B"),
    (Angle_elem_position.bul2, Angle_elem_position.bdr1, Side_position.down) -> Array("U'", "L", "U'", "L'", "B'", "U2", "B"),
    (Angle_elem_position.bul3, Angle_elem_position.bdr1, Side_position.down) -> Array("L", "U'", "L'"),
    (Angle_elem_position.bur1, Angle_elem_position.bdr1, Side_position.down) -> Array("U'", "B'", "U", "B"),
    (Angle_elem_position.bur2, Angle_elem_position.bdr1, Side_position.down) -> Array("U", "L", "U'", "L'"),
    (Angle_elem_position.bur3, Angle_elem_position.bdr1, Side_position.down) -> Array("L", "U'", "L'", "B'", "U2", "B"),
    (Angle_elem_position.bdl1, Angle_elem_position.bdr1, Side_position.down) -> Array("B", "U", "B2", "U2", "B"),
    (Angle_elem_position.bdl2, Angle_elem_position.bdr1, Side_position.down) -> Array("R'", "U2", "R", "B'", "U", "B"),
    (Angle_elem_position.bdl3, Angle_elem_position.bdr1, Side_position.down) -> Array("L", "R'", "U'", "R", "L'"),
    (Angle_elem_position.bdr1, Angle_elem_position.bdr1, Side_position.down) -> Array(""),
    (Angle_elem_position.bdr2, Angle_elem_position.bdr1, Side_position.down) -> Array("L", "U2", "L'", "B'", "U2", "B"),
    (Angle_elem_position.bdr3, Angle_elem_position.bdr1, Side_position.down) -> Array("B'", "U2", "B", "L", "U2", "L'"),

    (Angle_elem_position.ful1, Angle_elem_position.bdl1, Side_position.down) -> Array("B", "U2", "B'"),
    (Angle_elem_position.ful2, Angle_elem_position.bdl1, Side_position.down) -> Array("R'", "U2", "R"),
    (Angle_elem_position.ful3, Angle_elem_position.bdl1, Side_position.down) -> Array("U2", "R'", "U", "R", "B", "U2", "B'"),
    (Angle_elem_position.fur1, Angle_elem_position.bdl1, Side_position.down) -> Array("B", "U'", "B'"),
    (Angle_elem_position.fur2, Angle_elem_position.bdl1, Side_position.down) -> Array("U", "R'", "U2", "R"),
    (Angle_elem_position.fur3, Angle_elem_position.bdl1, Side_position.down) -> Array("U'", "R'", "U", "R", "B", "U2", "B'"),
    (Angle_elem_position.fdl1, Angle_elem_position.bdl1, Side_position.down) -> Array("F", "B", "U2", "B'", "F'"),
    (Angle_elem_position.fdl2, Angle_elem_position.bdl1, Side_position.down) -> Array("L'", "B", "U2", "B'", "L"),
    (Angle_elem_position.fdl3, Angle_elem_position.bdl1, Side_position.down) -> Array("F", "R'", "U2", "R", "F'"),
    (Angle_elem_position.fdr1, Angle_elem_position.bdl1, Side_position.down) -> Array("R", "U", "R'", "B", "U2", "B'"),
    (Angle_elem_position.fdr2, Angle_elem_position.bdl1, Side_position.down) -> Array("F'", "B", "U'", "B'", "F"),
    (Angle_elem_position.fdr3, Angle_elem_position.bdl1, Side_position.down) -> Array("R", "U", "R2", "U2", "R"),
    (Angle_elem_position.bul1, Angle_elem_position.bdl1, Side_position.down) -> Array("U", "B", "U'", "B'"),
    (Angle_elem_position.bul2, Angle_elem_position.bdl1, Side_position.down) -> Array("U2", "R'", "U2", "R"),
    (Angle_elem_position.bul3, Angle_elem_position.bdl1, Side_position.down) -> Array("R'", "U", "R", "B", "U2", "B'"),
    (Angle_elem_position.bur1, Angle_elem_position.bdl1, Side_position.down) -> Array("U'", "B", "U2", "B'"),
    (Angle_elem_position.bur2, Angle_elem_position.bdl1, Side_position.down) -> Array("U", "R'", "U", "R", "B", "U2", "B'"),
    (Angle_elem_position.bur3, Angle_elem_position.bdl1, Side_position.down) -> Array("R'", "U", "R"),
    (Angle_elem_position.bdl1, Angle_elem_position.bdl1, Side_position.down) -> Array(""),
    (Angle_elem_position.bdl2, Angle_elem_position.bdl1, Side_position.down) -> Array("R'", "U2", "R", "B", "U2", "B'"),
    (Angle_elem_position.bdl3, Angle_elem_position.bdl1, Side_position.down) -> Array("B", "U2", "B'", "R'", "U2", "R"),
    (Angle_elem_position.bdr1, Angle_elem_position.bdl1, Side_position.down) -> Array("B'", "U'", "B2", "U2", "B'"),
    (Angle_elem_position.bdr2, Angle_elem_position.bdl1, Side_position.down) -> Array("L", "U2", "L'", "B", "U'", "B'"),
    (Angle_elem_position.bdr3, Angle_elem_position.bdl1, Side_position.down) -> Array("R'", "L", "U", "L'", "R")
  )
}
